- src/actions/MigrationActions/MigrationActions.js
- src/components/ApiCaller/ApiCaller.js
- src/stores/UserStore/UserStore.js
Fixes "Malformed request url" issue, doesn't send the request until user is scoped CORWEB-24
> Fixes "Malformed request url" issue CORWEB-24

- src/actions/UserActions/UserActions.js
- src/stores/ConnectionsStore/ConnectionsStore.js
- src/stores/UserStore/UserStore.js
> Redirects to cloud-endpoints instead of replicas when there are no connections CORWEB-29

- src/constants/CloudLabels.js
- src/stores/ConnectionsStore/ConnectionsStore.js
Fixed an issue where a boolean field had "true" has a default value.
> Added hard coded missing labels CORWEB-65

- src/constants/CloudLabels.js
Reverts cloudbase/coriolis-web#33
> Revert "Added proper name labels for 'migr_worker_use_fip' and 'migr_worker_u…"

- src/components/ReplicaList/ReplicaList.js
- src/stores/MigrationStore/MigrationStore.js
Keep migrations list sorted by creation date.
> Sort replicas by last execution date CORWEB-56

- src/actions/MigrationActions/MigrationActions.js
Convert data from the format used by the UI to the original format required by the server.
> Make sure to send the correct data type back when using the wizard CORWEB-71

- src/components/App/App.scss
- src/components/MigrationWizard/MigrationWizard.scss
- src/components/SearchBox/SearchBox.js
- src/components/SearchBox/SearchBox.scss
- src/components/WizardVms/WizardVms.js
- src/components/WizardVms/WizardVms.scss
- src/components/variables.scss
- src/stores/WizardStore/WizardStore.js
Don't blank the instances list while searching, instead show a loading spinner in the search box.
Don't blank the instances list while changing the page, instead show loading spinner.
Small WizardVms.js and SearchBox.js refactoring.
Fix JS error with caching and pagination.
> Improve wizard instances search loading and pagination CORWEB-39 CORWEB-78

- src/components/WizardNetworks/WizardNetworks.js
- src/components/WizardSummary/WizardSummary.js
- src/config.sample.js
Removed schedule body from summary.
> Removed schedule page from wizard CORWEB-75

- src/components/ReplicaExecutions/ReplicaExecutions.js
- src/components/ReplicaExecutions/ReplicaExecutions.scss
Included the ability to copy it to clipboard.
Refactored executions header CSS, removing floats and absolute positioning.
> Added ID label to replica executions list CORWEB-60

- src/components/ReplicaView/ReplicaView.js
- src/components/Table/Table.js
- src/components/Tasks/Tasks.js
Reset the open state of the running execution's rows to keep only the running tasks open.
> Poll replica status if current status is running CORWEB-23

- src/constants/CloudLabels.js
- src/stores/ConnectionsStore/ConnectionsStore.js
Refactor field sorting in ConnectionStore.js.
> Refactor 'azure' code in ConnectionStore.js file CORWEB-62

- src/components/AddCloudConnection/AddCloudConnection.scss
- src/components/CloudItem/CloudItem.scss
- src/components/MigrationWizard/MigrationWizard.scss
- src/components/Switch/Switch.scss
- src/components/WizardSource/WizardSource.js
- src/components/WizardSource/WizardSource.scss
- src/components/WizardTarget/WizardTarget.js
- src/components/WizardTarget/WizardTarget.scss
- src/components/variables.scss
Remove 'float' from CSS, use instead flex grids.
Removed 'nth-child' from CSS.
Remove scroll, if not necessary, from Add Cloud Connection endpoints list.
> Wizard style refactoring fixing FF issues on windows CORWEB-91

- src/components/AddCloudConnection/AddCloudConnection.js
- src/constants/CloudLabels.js
Boolean type is now supported, no need to convert it to string.
> Leave boolean values unchanged when editing endpoint CORWEB-95

- src/components/AddCloudConnection/AddCloudConnection.js
- src/components/AddCloudConnection/AddCloudConnection.scss
- src/components/CloudConnectionsView/CloudConnectionsView.js
- src/components/CloudItem/CloudItem.js
- src/components/ConfirmationDialog/ConfirmationDialog.js
- src/components/EndpointList/EndpointList.js
- src/components/NewModal/NewModal.js
- src/components/NewModal/NewModal.scss
- src/components/NewModal/package.json
- src/components/UserOverview/UserOverview.js
Dynamically center the modal on center of the page. Works with browser resize and content change.
Removes a lot of mostly duplicated 'modalStyle' code.
> Refactored Modal into a new component CORWEB-98

- src/components/App/App.scss
- src/components/LoginPage/LoginPage.js
- src/components/LoginPage/LoginPage.scss
Autofill will no longer conflict with what the user currently types in slow connection.
Updated the input's disabled state style.
Should we have some kind of loading animation while the user waits?
> Disable login inputs until the page is completely loaded CORWEB-92

- src/components/AddCloudConnection/AddCloudConnection.js
- src/components/AddCloudConnection/AddCloudConnection.scss
- src/components/WizardOptions/WizardOptions.js
- src/components/WizardOptions/WizardOptions.scss
For now, applicable to Add Cloud Connection popup and Wizard Options.
> Change required text input style based on Sketch CORWEB-101

- src/components/ApiCaller/ApiCaller.js
- src/components/LoginPage/LoginPage.js
- src/components/LoginPage/LoginPage.scss
- src/stores/NotificationsStore/NotificationsStore.js
- src/stores/UserStore/UserStore.js
Fix login page reload after incorrect login info
> Add styled message if login info is incorrect CORWEB-110

- src/constants/CloudLabels.js
- src/stores/ConnectionsStore/ConnectionsStore.js
Fix typo in CloudLabels for one of the options in enum
> Show dropdown in Wizard's options if field type is text and has an 'enum' option CORWEB-118

- src/components/molecules/Dropdown/Dropdown.jsx
- src/components/molecules/Dropdown/story.jsx
Reproducible on long lists like the scheduler's days list.
Bug credit to @gabriel-samfira
> Don't close dropdown if user clicks its scrollbar

- src/components/molecules/SideMenu/SideMenu.jsx
Properly align the button's elements when opened.
> Improve `SideMenu`s toggle button animation

- src/components/atoms/TextInput/TextInput.jsx
The text input's value should now be better aligned.
> Fix text input's value misalignment

- src/components/organisms/WizardEndpointList/WizardEndpointList.jsx
- src/components/organisms/WizardInstances/WizardInstances.jsx
Scroll can be made visible on Mac in General settings.
> Fix wizard's providers list when scroll is visible

- src/components/atoms/Button/Button.jsx
- src/components/molecules/Modal/Modal.jsx
- src/components/organisms/AlertModal/AlertModal.jsx
- src/components/organisms/Endpoint/Endpoint.jsx
- src/components/organisms/ReplicaExecutionOptions/ReplicaExecutionOptions.jsx
- src/components/organisms/ReplicaMigrationOptions/ReplicaMigrationOptions.jsx
- src/components/organisms/WizardPageContent/WizardPageContent.jsx
- src/components/pages/WizardPage/WizardPage.jsx
- src/plugins/endpoint/azure/ContentPlugin.jsx
- src/utils/KeyboardManager.js
Esc can now be used for cancelling an alert / confirmation modal and
Enter can be used for confirmation, i.e. when deleting something.
> Press Enter to confirm in 'confirmation' modals

- package.json
- src/components/molecules/TaskItem/TaskItem.jsx
- src/components/organisms/Tasks/Tasks.jsx
- yarn.lock
Also includes 'Depends On' click support in execution tasks.
> Redo `TaskItem` layout - CORWEB 166

- src/components/organisms/MainDetails/index.jsx
- src/types/MainItem.js
Applicable to Replica and Migration details page.
Also shows a new 'Instances' field listing all instances used in a
migration or replica.
> Show destination env properties in Details page CORWEB-169

- src/components/organisms/MainDetails/index.jsx
Applicable to all fields found in Replica / Migration details page.
> Show Copy button for all Replica/Migration fields CORWEB-170

- src/stores/ReplicaStore.js
Occasionally after finishing the wizard and after being redirected to
the replica's execution page, the first execution would be added twice.
This also fixes an issue where, after finishing the wizard with multiple
replicas separated per VM, the replica list page wouldn't list the
current running execution for a few seconds for the newly created ones.
> Fix execution being added twice

- src/components/pages/NotFoundPage/index.jsx
Use any invalid path to view it. Ex.: 'http://localhost:3000/blabla'.
> Add basic style to `NotFoundPage`

- src/components/pages/WizardPage/index.jsx
The `Wait.for` function is no longer necessary in `WizardPage`. Since
actions now return a `Promise`, we can wait for the promise to resolve.
> Refactor to use `Promise` instead of `Wait.for`

- src/components/pages/AssessmentsPage/index.jsx
Use the same refactoring of the project changing process used in other
pages.
Disable polling while the new endpoint modal is open, same is in the
other pages.
> Apply changes from other pages to Planning page

- src/components/organisms/MainDetails/index.jsx
Render Replica / Migration description and instances on multiple lines
if necessary, instead of truncating the text to one line. Allow copying
of multiline text.
Don't render the properties table if there are no properties available.
> Improve details page for Replica / Migration

- src/components/organisms/WizardSummary/index.jsx
Handle long and / or multiline property names and values.
> Improve Wizard Summary 'Options' display

- src/utils/ApiCaller.js
Any error while on login page is already shown above the login form.
> Disable notifications while on Login page

- src/components/pages/EndpointsPage/index.jsx
If some or all of the selected endpoints are in use by replicas or
migrations, deletion is not allowed and a message is presented.
This is similar to what happens when trying to delete an used endpoint
from its details page.
> Don't allow multiple endpoints delete if in use

- src/components/organisms/EndpointDetailsContent/index.jsx
- src/components/pages/EndpointDetailsPage/index.jsx
It shows in how many replicas/migrations the endpoint is used and their
names.
This new field and the 'description' field is not ellipsed like the
other fields, instead they are rendered on multiple lines if they don't
fit in one line.
> Add 'Used in ...' info to endpoint details page

- src/components/atoms/DropdownButton/index.jsx
- src/components/molecules/DatetimePicker/index.jsx
The `DateTimePicker` dropdown is now positioned dynamically based on
display space available and scroll position.
> Improve `DateTimePicker` when scrolled

- src/components/molecules/AssessedVmListItem/index.jsx
- src/components/organisms/AssessmentDetailsContent/index.jsx
Fix the tables layout disturbances caused by the widening of the layout.
> Fix assessment details tables layout

- src/components/molecules/DatetimePicker/index.jsx
- src/components/molecules/Dropdown/index.jsx
- src/utils/DomUtils.js
- yarn.lock
The dropdown list now follows the parent container's scrolling position
while opened.
Also, if, while scrolling, the dropdown button is no longer in the
viewport, the dropdown list automatically closes.
This also solves the same issues with the `DateTimePicker` component.
> Fix scrolling while a dropdown list is opened

- src/components/atoms/CopyMultilineValue/index.jsx
- src/components/organisms/EndpointDetailsContent/index.jsx
- src/components/organisms/MainDetails/index.jsx
Extract duplicated code related to multiline text copying into a
separate component.
> Refactor copying multiline text

- src/plugins/endpoint/openstack/ContentPlugin.jsx
- src/plugins/endpoint/openstack/SchemaPlugin.js
- src/types/Field.js
Reverts cloudbase/coriolis-web#223.
> Revert "Add 2 more fields to Openstack API v3 simple form"

- src/components/molecules/DropdownLink/index.jsx
- src/components/molecules/EndpointField/index.jsx
- src/plugins/endpoint/openstack/ContentPlugin.jsx
- src/plugins/endpoint/openstack/SchemaPlugin.js
The 'Project Domain' and 'User Domain' fields are not selected properly
when editing an Openstack V3 endpoint
> Fix issues with editing Openstack V3 endpoint

- src/components/App.jsx
- src/components/atoms/CopyMultilineValue/index.jsx
- src/components/atoms/CopyValue/index.jsx
- src/components/molecules/ScheduleItem/index.jsx
- src/components/molecules/TaskItem/index.jsx
- src/components/organisms/DetailsPageHeader/index.jsx
- src/components/organisms/Endpoint/index.jsx
- src/components/organisms/EndpointValidation/index.jsx
- src/components/organisms/LoginForm/index.jsx
- src/components/organisms/Notifications/index.jsx
- src/components/organisms/PageHeader/index.jsx
- src/components/organisms/ReplicaDetailsContent/index.jsx
- src/components/organisms/WizardPageContent/index.jsx
- src/components/pages/AssessmentDetailsPage/index.jsx
- src/components/pages/AssessmentsPage/index.jsx
- src/components/pages/EndpointDetailsPage/index.jsx
- src/components/pages/EndpointsPage/index.jsx
- src/components/pages/LoginPage/index.jsx
- src/components/pages/MigrationDetailsPage/index.jsx
- src/components/pages/MigrationsPage/index.jsx
- src/components/pages/ReplicaDetailsPage/index.jsx
- src/components/pages/ReplicasPage/index.jsx
- src/components/pages/WizardPage/index.jsx
- src/sources/AssessmentSource.js
- src/sources/WizardSource.js
- src/stores/MigrationStore.js
- src/stores/ProviderStore.js
- src/stores/ReplicaStore.js
- src/stores/UserStore.js
- src/utils/ApiCaller.js
Store references are class instances and should use lowercase, using uppercase should be reserved for referencing static class methods.
> Rename all store references to lowercase

- src/components/pages/EndpointsPage/index.jsx
- src/plugins/endpoint/default/SchemaPlugin.js
When creating or editing an endpoint, if a required field has no value
set, but it does have a default value, set the default value as the
actual value.
> Set default value if field is required CORWEB-172

- src/components/atoms/AutocompleteInput/images/arrow.js
- src/components/atoms/AutocompleteInput/index.jsx
- src/components/atoms/AutocompleteInput/story.jsx
- src/components/atoms/TextInput/index.jsx
- src/components/molecules/AutocompleteDropdown/index.jsx
- src/components/molecules/AutocompleteDropdown/story.jsx
- src/components/molecules/WizardOptionsField/index.jsx
- src/components/organisms/WizardPageContent/index.jsx
- src/components/pages/WizardPage/index.jsx
Applicable to long lists in Wizard Options page, like Azure's VM sizes,
Openstack's migration flavour names, OCI's shape names etc.
> Use a searchable dropdown component for long lists

- src/components/molecules/WizardOptionsField/index.jsx
- src/components/organisms/MainDetails/index.jsx
- src/components/organisms/WizardOptions/index.jsx
- src/components/organisms/WizardSummary/index.jsx
- src/plugins/endpoint/default/OptionsSchemaPlugin.js
- src/sources/WizardSource.js
- src/stores/WizardStore.js
Currently only 'security_groups' field in Openstack is of type 'array'.
> Add support for array fields in wizard options

- src/components/molecules/Dropdown/index.jsx
The checkmark symbol in a dropdown with multiple selection component is
now animated when selecting / deselecting items.
The label color is also updated when an item is selected.
> Animate multiple selection checkmark symbol

- src/components/organisms/WizardPageContent/WizardPageContent.jsx
- src/components/organisms/WizardSummary/WizardSummary.jsx
- src/components/pages/WizardPage/WizardPage.jsx
- src/stores/WizardStore.js
- src/types/WizardData.js
The React `render` method didn't get called because the schedules array
didn't get registered as an observable array in the `mobx` library.
> Fix schedules UI not updating in Wizard

- src/components/molecules/UserDropdown/UserDropdown.jsx
- src/components/organisms/DetailsPageHeader/DetailsPageHeader.jsx
- src/components/organisms/DetailsPageHeader/test.jsx
- src/components/organisms/Notifications/Notifications.jsx
- src/components/organisms/PageHeader/PageHeader.jsx
- src/utils/ApiCaller.js
- src/utils/ApiLogger.js
The log cand be downloaded as a JSON file from the User Dropdown menu.
> Log all API calls to `localStorage`

- src/components/atoms/DropdownButton/DropdownButton.jsx
- src/components/atoms/DropdownButton/images/arrow.js
- src/components/organisms/WizardNetworks/images/arrow.svg
- src/components/organisms/WizardStorage/images/arrow.svg
Applies to Dropdown component, Wizard Networks and Storage.
> Use darker color for 'arrow' icons

- src/components/organisms/MainDetails/MainDetails.jsx
- src/components/organisms/MainDetails/test.jsx
- src/plugins/endpoint/default/OptionsSchemaPlugin.js
- src/sources/WizardSource.js
- src/types/MainItem.js
Remove the `description` field from replica's `destination_environment`.
> Use the `notes` field for replica description

- src/components/organisms/WizardOptions/WizardOptions.jsx
- src/components/organisms/WizardPageContent/WizardPageContent.jsx
- src/components/organisms/WizardStorage/WizardStorage.jsx
- src/components/organisms/WizardSummary/WizardSummary.jsx
- src/components/pages/WizardPage/WizardPage.jsx
- src/sources/EndpointSource.js
- src/stores/EndpointStore.js
- src/types/Endpoint.js
`Storage` type now holds the `storage_backend` array and
`config_default` string.
> Use the updated storage API schema

- src/components/pages/LoginPage/LoginPage.jsx
Reproducible by zooming in or resizing the browser to a very small size.
> Fix `Cloudbase` logo overlapping login form

- src/components/organisms/ChooseProvider/ChooseProvider.jsx
- src/components/organisms/WizardPageContent/WizardPageContent.jsx
- src/sources/ProviderSource.js
Applicable to wizard source and target pages and when creating a new
endpoint.
> Sort providers by name

- src/plugins/endpoint/default/ConnectionSchemaPlugin.js
- src/types/Field.js
- src/utils/LabelDictionary.js
If the schema provided a title or a label for a field, use it.
> Load field label and description from schema

- src/utils/ApiCaller.js
The app would not redirect to the login page, if a request fails with
401. Reproducible on production build only.
Cause by removing the '#' from URL feature, since `window.location.hash`
is no longer available on production.
> Fix redirection fail on request with status 401

- config.js
- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/pages/WizardPage/WizardPage.jsx
- src/constants.js
- src/types/Config.js
Storage mapping providers are removed from config file and are instead
detected automatically.
> Automatically detect storage mapping support CORWEB-195

- src/components/molecules/MainListItem/MainListItem.jsx
- src/components/molecules/MainListItem/images/schedule.svg
- src/components/organisms/MainList/MainList.jsx
- src/components/pages/ReplicasPage/ReplicasPage.jsx
- src/sources/ScheduleSource.js
- src/stores/ScheduleStore.js
- src/types/Schedule.js
Currently an API query needs to be made for all replicas in order to
find out if it has a schedule item enabled.
This may pose performance issues when there are a lot of replicas.
> Use 'Schedule' icon if replica is scheduled CORWEB-196

- src/components/molecules/ActionDropdown/ActionDropdown.jsx
- src/components/molecules/MainListFilter/MainListFilter.jsx
- src/components/molecules/MainListFilter/test.jsx
- src/components/organisms/FilterList/FilterList.jsx
- src/components/organisms/FilterList/test.jsx
- src/components/pages/EndpointsPage/EndpointsPage.jsx
- src/components/pages/MigrationsPage/MigrationsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/components/pages/ReplicasPage/ReplicasPage.jsx
Replicas List page now has more actions available. To support this the
whole list bulk operation has been refactored.
All list pages have been updated to use the new actions button layout.
Also resolves CORWEB-208
> Update Bulk Actions button in lists pages

- src/sources/ProjectSource.js
Reproducible when CORIOLIS_URL is just '/'.
> Fix project details page not loading

- package.json
- yarn.lock
Updated `mem` to 4.4.0 as older versions have a security vulnerability.
> Fix `mem` version dependency

- config.js
- src/sources/UserSource.js
- src/types/Config.js
- src/utils/ObjectUtils.js
A configurable list of users (`config.js` -> `hiddenUsers`) to hide in
the UI.
> Hide a list of Coriolis users in the UI

- config.js
- src/components/molecules/MainDetailsTable/test.jsx
- src/components/molecules/Panel/Panel.jsx
- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/organisms/WizardOptions/WizardOptions.jsx
- src/sources/ReplicaSource.js
- src/stores/MigrationStore.js
- src/stores/ProviderStore.js
- src/types/MainItem.js
Add ability to edit the replica's source options for supported providers
(AWS).
> Add Edit Replica source options

- src/utils/ObjectUtils.js
The function didn't work properly, since it didn't get resolved under
certain circumstances.
> Fix `waitFor` utility function

- src/sources/MigrationSource.js
- src/sources/ReplicaSource.js
If there are more than 2 tasks running and a couple of completed ones
just bellow them, add the completed ones on top of the running ones.
Fragment tasks - meaning, reset the sorting algorithm - when
encountering tasks which don't have a status of 'COMPLETED' or 'ERROR'.
For example, the tasks:
RUNNING, COMPLETED, RUNNING, COMPLETED, PENDING, RUNNING, RUNNING,
COMPLETED
Will be sorted into:
COMPLETED, COMPLETED, RUNNING, RUNNING, PENDING, COMPLETED, RUNNING,
RUNNING
A set of tasks like: RUNNING, COMPLETED, COMPLETED would remain
unchanged, since there's only 1 running task.
> Improve tasks sorting when there are parallel ones

- src/plugins/endpoint/ovm/OptionsSchemaPlugin.js
Applicable to OVM as destination provider.
> Add `migr_template_name_map` to Wizard Options UI

- src/components/pages/UserDetailsPage/UserDetailsPage.jsx
@smiclea @thenoizz please check this, not sure if there are any other references for the label.
> UserDetailsPage.jsx: Fix typo

- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/organisms/WizardNetworks/WizardNetworks.jsx
- src/components/organisms/WizardStorage/WizardStorage.jsx
Network and Storage page appears with no padding in Edit Replica modal.
> Fix Edit Replica layout issue in Network page

- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/organisms/WizardOptions/WizardOptions.jsx
- src/components/organisms/WizardPageContent/WizardPageContent.jsx
- src/components/organisms/WizardStorage/WizardStorage.jsx
Options and Storage layout appears incorrect in Wizard and Edit Replica
pages.
> Fix Options and Storage screens layout

- src/components/molecules/NotificationDropdown/NotificationDropdown.jsx
Fixes an issue where the app crashes when clicking the notification bell
button when there are no notification items.
> Fix crash when clicking notification bell button CORWEB-221

- package.json
- server/main.js
- server/router.js
- src/components/molecules/FieldInput/FieldInput.jsx
- src/components/organisms/ChooseProvider/ChooseProvider.jsx
- src/components/organisms/Endpoint/Endpoint.jsx
- src/components/organisms/Licence/Licence.jsx
- src/components/organisms/PageHeader/PageHeader.jsx
- src/components/pages/EndpointDetailsPage/EndpointDetailsPage.jsx
- src/components/pages/EndpointsPage/EndpointsPage.jsx
- src/plugins/endpoint/azure/ConnectionSchemaPlugin.js
- src/plugins/endpoint/azure/ContentPlugin.jsx
- src/stores/EndpointStore.js
- src/stores/LicenceStore.js
- src/stores/ProviderStore.js
- src/types/ZipContent.js
- src/utils/ApiLogger.js
- src/utils/Config.js
- src/utils/DomUtils.js
- src/utils/ObjectUtils.js
- yarn.lock
Endpoints can be exported in bulk from the endpoints list or
individually from their details page.
An endpoint can be imported from a JSON file by choosing New Endpoint
from the dropdown input.
> Add ability to export / import endpoints from JSON

- src/components/molecules/AutocompleteDropdown/AutocompleteDropdown.jsx
- src/components/molecules/Dropdown/Dropdown.jsx
Fix an issue where horizontal scroll would appear if the dropdown list
had items with long words.
> Fix horizontal scroll appearing in dropdown list

- src/components/organisms/EditReplica/EditReplica.jsx
If the destination provider errors out, show an error message and
disable the 'Update' button.
If the destination provider errors out while recreating a migration,
show an error message, but don't disable the 'Create' button.
> Show error message on Edit Replica dest. fail CORWEB-223

- src/components/atoms/Stepper/Stepper.jsx
- src/components/atoms/Stepper/images/down.svg
- src/components/atoms/Stepper/images/up.svg
- src/components/atoms/Stepper/package.json
- src/components/molecules/FieldInput/FieldInput.jsx
- src/components/organisms/WizardOptions/story.jsx
If an integer field has no minimum and no maximum, or the difference
between them is too large, use a numerical stepper component.
Otherwise, keep using a dropdown with all the available numerical values.
> Add support for integer fields with no min. / max.

- src/components/atoms/TextInput/TextInput.jsx
- src/components/molecules/AutocompleteDropdown/AutocompleteDropdown.jsx
- src/components/molecules/AutocompleteDropdown/story.jsx
- src/components/molecules/Dropdown/Dropdown.jsx
- src/components/molecules/Dropdown/story.jsx
- src/components/molecules/PropertiesTable/story.jsx
- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/organisms/WizardNetworks/WizardNetworks.jsx
- src/components/organisms/WizardStorage/WizardStorage.jsx
Fixes storage and network mapping screen layout issues when using long
instances name.
Fixes embedded required field symbol layout (embedded fields are the
ones rendered inside properties table for object type fields).
> Fix mapping screens and embedded required layouts

- config.js
- src/components/molecules/FieldInput/FieldInput.jsx
- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/organisms/Endpoint/Endpoint.jsx
- src/components/organisms/WizardOptions/WizardOptions.jsx
- src/components/organisms/WizardPageContent/WizardPageContent.jsx
- src/components/organisms/WizardStorage/WizardStorage.jsx
- src/components/organisms/WizardSummary/WizardSummary.jsx
- src/plugins/endpoint/default/ConnectionSchemaPlugin.js
- src/plugins/endpoint/default/OptionsSchemaPlugin.js
- src/plugins/endpoint/index.js
- src/plugins/endpoint/openstack/ContentPlugin.jsx
- src/plugins/endpoint/openstack/OptionsSchemaPlugin.js
- src/stores/WizardStore.js
- src/types/Field.js
- src/types/Schema.js
- src/utils/LabelDictionary.js
- src/utils/ObjectUtils.js
Includes support for an updated source schema containing replica export
mechanism options and its associated sub-options.
Includes support for an updated connection info schema containing Ceph
platform options.
> Update Openstack source and conn. info schemas

- src/components/pages/LogsPage/DownloadsContent.jsx
- src/components/pages/LogsPage/LogsPage.jsx
- src/stores/LogStore.js
Accessible from the logs page.
> Add ability to download diagnostics JSON file

- src/utils/LabelDictionary.js
Add entry to the enum fields for which its items will be parsed by the
dictionary.
Also includes lowercasing the words as part of the label dictionary
parsing process.
> Add a new entry to the label dictionary

- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/organisms/WizardOptions/WizardOptions.jsx
- src/components/organisms/WizardPageContent/WizardPageContent.jsx
- src/components/organisms/WizardStorage/WizardStorage.jsx
- src/components/organisms/WizardStorage/test.jsx
- src/components/organisms/WizardSummary/WizardSummary.jsx
- src/components/pages/WizardPage/WizardPage.jsx
- src/plugins/endpoint/default/OptionsSchemaPlugin.js
- src/sources/AssessmentSource.js
- src/sources/MigrationSource.js
- src/sources/ReplicaSource.js
- src/sources/WizardSource.js
- src/stores/MigrationStore.js
- src/stores/ReplicaStore.js
- src/stores/WizardStore.js
Besides moving the Default Storage dropdown from Wizard Options screen
to Wizard Storage screen, the code logic has also been refactored to
reflect this.
> Move default storage from options to storage

- src/components/organisms/ChooseProvider/ChooseProvider.jsx
- src/components/organisms/ChooseProvider/MultipleUploadedEndpoints.jsx
- src/components/organisms/ChooseProvider/images/delete-hover.svg
- src/components/organisms/ChooseProvider/images/delete.svg
- src/components/organisms/Licence/Licence.jsx
- src/components/organisms/PageHeader/PageHeader.jsx
- src/components/organisms/WizardScripts/WizardScripts.jsx
- src/components/pages/EndpointsPage/EndpointsPage.jsx
- src/stores/EndpointStore.js
- src/types/Endpoint.js
- src/utils/FileUtils.js
- src/utils/ObjectUtils.js
Uploading and drag / dropping multiple .endpoint and zipped .endpoint
files is now supported.
Any combination of .endpoint and .zip files is supported.
All uploaded endpoints are validated after they are added.
> Upload multi .endpoint and zipped .endpoint files

- config.js
- src/components/molecules/FieldInput/FieldInput.jsx
- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/organisms/MainDetails/MainDetails.jsx
- src/components/organisms/WizardOptions/WizardOptions.jsx
- src/components/organisms/WizardPageContent/WizardPageContent.jsx
- src/components/organisms/WizardSummary/WizardSummary.jsx
- src/plugins/endpoint/default/ConnectionSchemaPlugin.js
- src/plugins/endpoint/default/OptionsSchemaPlugin.js
- src/plugins/endpoint/openstack/OptionsSchemaPlugin.js
- src/plugins/endpoint/ovm/OptionsSchemaPlugin.js
- src/sources/ProviderSource.js
- src/sources/Schemas.js
- src/utils/LabelDictionary.js
Make extra options (destination and source) API calls based on AWS field
values.
> Add AWS to extra options API calls list

- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/organisms/WizardStorage/WizardStorage.jsx
- src/components/organisms/WizardStorage/story.jsx
This should make the 'Default Storage' option fit better with the rest
of the elements in the Wizard Storage screen.
> Change the layout of the 'Default Storage' option

- server/api/ConfigApi.js
Services URLs would not be set, if there was a modding JSON file
provided, with no services URLs override in it.
> Fix an issue where services URLs were not set

- .flowconfig
- package.json
- yarn.lock
Fix some NPM dependencies security vulnerabilities found by GitHub
security alert bot.
> Fix NPM dependencies security vulnerabilities

- src/stores/ProviderStore.js
In certain cases the Wizard Options page might have displayed options
from a previously used endpoint. This was due to some concurrency issues
where a previous endpoint's response might come later than the currently
selected endpoint's response.
> Fix Wizard showing data for a different endpoint

- package.json
- yarn.lock
https://github.com/advisories/GHSA-p9pc-299p-vxgp
> Fix NPM package security alert

- src/sources/EndpointSource.ts
Fixes an issue where invalid data was sent to the API when trying to
duplicate an endpoint.
> Fix endpoint duplicate issue

- package.json
- src/@types/Task.ts
- src/components/atoms/ProgressBar/ProgressBar.tsx
- src/components/molecules/TaskItem/TaskItem.tsx
- src/components/molecules/TaskItem/story.tsx
- src/sources/MigrationSource.ts
- src/sources/ReplicaSource.ts
1. The task updates are now sorted by the newly added `index` field
instead of creation date.
2. The progress bar for the task updates is calculated based on newly
added fields with the previous text base parsing method as a fallback.
> Update task updates sorting and progress fields CORWEB-250

- src/components/organisms/WizardPageContent/WizardPageContent.tsx
The 'Reload Options' button, visible in Source Options and Destination
Options, is now hidden while the options are being loaded.
The same philosophy is now also applied to 'Reload Networks' in Network
Mapping page.
> Hide 'Reload Options' while options are loading

- src/@types/MainItem.ts
- src/components/molecules/MainListItem/MainListItem.tsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.tsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.tsx
- src/sources/NotificationSource.ts
This also applies to the Recent Activity module in the Dashboard page.
> Use the "Title" / "notes" field in notifications

- src/components/molecules/UserDropdown/UserDropdown.tsx
- src/components/molecules/UserDropdown/images/openInNewImage.ts
- src/components/organisms/DetailsPageHeader/DetailsPageHeader.tsx
There's a new Coriolis Help link visible when opening the user dropdown
menu.
> Add link to Coriolis Help page in user drop menu

- src/@types/Field.ts
- src/components/organisms/EditReplica/EditReplica.tsx
- src/components/organisms/WizardOptions/WizardOptions.tsx
- src/constants.ts
- src/plugins/endpoint/default/OptionsSchemaPlugin.ts
- src/plugins/endpoint/openstack/OptionsSchemaPlugin.ts
- src/plugins/endpoint/ovm/OptionsSchemaPlugin.ts
- src/sources/ReplicaSource.ts
- src/sources/Schemas.ts
- src/stores/ReplicaStore.ts
- src/stores/WizardStore.ts
Hide all the fields in Source Options when choosing to use OVM Exporter.
> Add 'Use OVM Exporter' field support

- src/components/organisms/MinionEndpointModal/MinionEndpointModal.tsx
- src/components/organisms/MinionPoolModal/MinionPoolModal.tsx
- src/components/organisms/MinionPoolModal/MinionPoolModalContent.tsx
- src/components/pages/MinionPoolDetailsPage/MinionPoolDetailsPage.tsx
- src/plugins/endpoint/default/MinionPoolSchemaPlugin.ts
- src/plugins/endpoint/index.ts
- src/plugins/endpoint/openstack/MinionPoolSchemaPlugin.ts
- src/sources/MinionPoolSource.ts
- src/sources/Schemas.ts
- src/stores/MinionPoolStore.ts
Updated the minion pool feature to support providers which require extra
'options' API calls.
Added plugin architecture for minion pool related API request data
handling.
> Add OCI provider minion pool support CORWEB-258

- src/components/organisms/MinionPoolModal/MinionPoolModal.tsx
Minion pools couldn't be updated when its provider uses multiple
destination option calls to retrieve field values.
This includes support and validation for the situation where an old
value can no longer be found in the new `enum` values of a property.
> Fix an issue where minion pool couldn't be updated

- .githooks/pre-commit
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.tsx
- src/stores/ReplicaStore.ts
- src/utils/ApiCaller.ts
- src/utils/ApiCallerHandlers.ts
Moved the logic from classic promise type functions to async / await.
Split the error handling code into a separate file.
> Refactor the API caller class

- package.json
- yarn.lock
Upgrade "nth-check" NPM package version.
> Fix Github dependebot security alert

- src/components/atoms/StatusIcon/StatusIcon.tsx
- src/components/molecules/ScheduleItem/ScheduleItem.tsx
- src/components/molecules/ScheduleItem/story.tsx
- src/components/organisms/ReplicaDetailsContent/ReplicaDetailsContent.tsx
- src/components/organisms/Schedule/Schedule.tsx
- src/stores/ScheduleStore.ts
New loading animations are shown for different schedule component
operations.
The user now has an indication that a scheduling request is being
performed when adding, updating and removing a schedule item.
> Improve waiting for schedule component requests

- package.json
- yarn.lock
Also fixes an issue with the `yarn install` process on Mac.
> Remove unused package.json dependency

- .eslintrc
- src/@types/Field.ts
- src/components/App.tsx
- src/components/modules/EndpointModule/EndpointLogos/story.tsx
- src/components/modules/MinionModule/MinionPoolDetailsContent/MinionPoolMainDetails.tsx
- src/components/modules/TransferModule/MainDetails/MainDetails.tsx
- src/components/modules/TransferModule/ReplicaMigrationOptions/ReplicaMigrationOptions.tsx
- src/components/modules/TransferModule/ScheduleItem/ScheduleItem.tsx
- src/components/modules/TransferModule/TransferDetailsTable/TransferDetailsTable.tsx
- src/components/modules/TransferModule/TransferItemModal/TransferItemModal.tsx
- src/components/modules/WizardModule/WizardScripts/WizardScripts.tsx
- src/components/modules/WizardModule/WizardStorage/WizardStorage.tsx
- src/components/modules/WizardModule/WizardSummary/WizardSummary.tsx
- src/components/smart/AssessmentsPage/AssessmentsPage.tsx
- src/components/smart/MigrationDetailsPage/MigrationDetailsPage.tsx
- src/components/smart/MigrationsPage/MigrationsPage.tsx
- src/components/smart/ReplicaDetailsPage/ReplicaDetailsPage.tsx
- src/components/smart/ReplicasPage/ReplicasPage.tsx
- src/components/smart/WizardPage/WizardPage.tsx
- src/sources/InstanceSource.ts
- src/sources/MigrationSource.ts
- src/sources/ProviderSource.ts
- src/sources/ScheduleSource.ts
- src/sources/WizardSource.ts
- src/stores/AzureStore.ts
- src/stores/InstanceStore.ts
- src/stores/MigrationStore.ts
- src/stores/ProviderStore.ts
- src/stores/ScheduleStore.ts
- src/stores/WizardStore.ts
Implement the rule with a maximum number of parameters (3) across the
codebase.
See https://eslint.org/docs/rules/max-params for more details about the
rule.
> Add 'max-param' ESLint rule across the codebase

- src/components/smart/PageHeader/PageHeader.tsx
- src/stores/ProjectStore.ts
When creating a new project, duplicate the existing bare metal endpoint
into it.
> Duplicate bare metal endpoint on new project

- src/components/modules/WizardModule/WizardOptions/WizardOptions.tsx
Fixes an issue where the horizontal scroll appears when editing a
replica.
> Fix horizontal scroll showing in Edit Replica

- babel.config.js
- config.ts
- jest.config.ts
- webpack.common.js
- webpack.dev.js
- webpack.prod.js
The new coding style was not previously applied to the project root files because the coding style is automatically enforced only for files in the 'src' and 'server' folders.
> Apply the new code style changes to root files

- package.json
- yarn.lock
Details: https://github.com/cloudbase/coriolis-web/security/dependabot/81
> Fix 3rd party dependency vulnerability

- src/components/modules/MetalHubModule/MetalHubListHeader/MetalHubListHeader.tsx
- src/components/modules/MetalHubModule/MetalHubListItem/MetalHubListItem.tsx
- src/components/smart/MetalHubServersPage/MetalHubServersPage.tsx
- src/sources/MetalHubSource.ts
Adds bulk remove and refresh actions by allowing multiple servers selection.
Improve server list item layout to avoid some column sizing issues.
Sort servers by "updated at" field.
> Improve Metal Hub Servers list page

- src/components/modules/MetalHubModule/MetalHubModal/MetalHubModal.tsx
- src/components/smart/MetalHubServerDetailsPage/MetalHubServerDetailsPage.tsx
- src/components/smart/MetalHubServersPage/MetalHubServersPage.tsx
- src/stores/MetalHubStore.ts
A validation process is now included when adding or editing a Bare Metal
Server. This is done by checking the active field.
Depends on #743
> Add validation process to Bare Metal Server modal

- src/components/modules/MinionModule/MinionPoolModal/MinionPoolModal.tsx
- src/stores/MinionPoolStore.ts
Sort minion pool migration images by selected OS Type and separate them using a delimiter.
> Sort minion pool migration images by OS Type

- src/components/modules/DashboardModule/DashboardLicence/DashboardLicence.tsx
Show full appliance ID in dashboard's licence module.
> Enhance copy functionality for appliance ID

- src/components/modules/EndpointModule/EndpointDetailsContent/EndpointDetailsContent.tsx
- src/components/modules/ProjectModule/ProjectDetailsContent/ProjectDetailsContent.tsx
- src/components/modules/TransferModule/MigrationDetailsContent/MigrationDetailsContent.tsx
- src/components/modules/TransferModule/ReplicaDetailsContent/ReplicaDetailsContent.tsx
- src/components/modules/UserModule/UserDetailsContent/UserDetailsContent.tsx
This commit updates the Details Content components by leveraging newer TypeScript features and enhancing readability, including optional chaining.
> Refactor details content components

- src/components/modules/EndpointModule/ChooseProvider/MultipleUploadedEndpoints.tsx
- src/components/modules/EndpointModule/EndpointModal/EndpointModal.tsx
- src/components/modules/EndpointModule/EndpointValidation/EndpointValidation.tsx
- src/components/modules/TransferModule/TaskItem/TaskItem.tsx
- src/components/ui/CopyMultilineValue/CopyMultilineValue.tsx
- src/components/ui/CopyValue/CopyValue.tsx
- src/utils/DomUtils.ts
Refactored the clipboard copy and copy notification handling in various components to use a single utility function.
- Updated `DomUtils.copyTextToClipboard` to accept success and error messages as optional parameters.
- Removed redundant notification handling code from components.
- Replaced the old clipboard copy method (it became deprecated) with the new `navigator.clipboard.writeText` method.
- Updated all components to use the new `DomUtils.copyTextToClipboard` function with appropriate messages.
> Refactor clipboard copy and notification handling

- src/components/smart/MigrationDetailsPage/MigrationDetailsPage.tsx
When recreating a migration from replica, after the migration is created, the user is redirected to the migration details page. However, the migration details page is not updated with the new migration and polling is not started.
This commit fixes that.
Also, a loading spinner is added to the Recreate Migration modal to indicate that the migration is being recreated.
Some small refactoring is also included.
> Fix Recreate Migration not redirecting properly

- package.json
- src/sources/UserSource.ts
- src/utils/ApiCaller.ts
- yarn.lock
Fixes for: https://github.com/cloudbase/coriolis-web/pull/827
> Fix TypeScript errors caused by `axios` dependency upgrade

- config.ts
- src/@types/Config.ts
- src/components/modules/ProjectModule/ProjectDetailsContent/ProjectDetailsContent.spec.tsx
- src/components/modules/ProjectModule/ProjectDetailsContent/ProjectDetailsContent.tsx
- src/components/modules/ProjectModule/ProjectMemberModal/ProjectMemberModal.tsx
- src/sources/ProjectSource.ts
- src/sources/UserSource.ts
This PR includes:
- Add `user role` filtering with configurable hidden roles
- Fix unit tests for `ProjectDetailsContent` component
> Add `user role` filtering functionality
