cloudbase/coriolis-web

- src/components/Table/Table.js
If a "mouse drag" operation is initiated, don't toggle the accordion.
> Allow text selection in task execution list without closing the accordion

- src/components/LoginPage/LoginPage.js
- src/components/ReplicaList/ReplicaList.js
- src/components/Table/Table.js
- src/components/WizardNetworks/WizardNetworks.js
- src/components/WizardOptions/WizardOptions.js
- src/stores/ConnectionsStore/ConnectionsStore.js
- src/stores/MigrationStore/MigrationStore.js
Also fixes an issue where changing a boolean field sends 'Yes/No' to the server instead of 'true/false'.
This uses the fact that the Dropdown's value is the label of the currently selected option. Ideally, the Dropdown should have a property called labelField (or something like that) that pulls the label from the 'options' property automatically.
> Show 'Yes/No' as default values instead of 'true/false' for boolean fields CORWEB-68

- src/components/MigrationList/MigrationList.js
- src/components/ReplicaList/ReplicaList.js
Switch to tasks page if migration is currently executing. This happens when selecting a replica / migration from replicas / migrations list.
This happens when selecting a replica / migration from replicas / migrations list.
> Switch to executions page if replica is currently executing CORWEB-19

- src/components/ReplicaExecutions/ReplicaExecutions.js
Select the next execution in line after an execution is deleted.
If it's the last execution that's deleted, select previous execution.
> Fix execution selection after deletion CORWEB-66

- src/components/ReplicaExecutions/ReplicaExecutions.js
- src/components/Table/Table.js
- src/components/Tasks/Tasks.js
Don't move the execution navigation every time the last execution is updated.
Move the navigation if a new execution was just added, but allow normal navigation after.
Show 'Cancel execution' button only for the currently running execution.
Allow deletion of previous executions while one is running.
> Allow navigation through executions while one is running CORWEB-67

- src/components/LoginPage/LoginPage.js
- src/components/LoginPage/LoginPage.scss
Used a 16px padding for top bottom and 32px padding for left right. 
If there are login providers the previous padding remains, 32px for top, left and right and 16px for bottom.
> Remove login separator if there are no login providers CORWEB-79

- src/constants/CloudLabels.js
Adds labels for storage API and storage authe ednpoints. These are needed for all OPC accounts created after April 2017.
> Add OPC storage auth and api endpoints

- src/components/Switch/Switch.js
- src/components/WizardOptions/WizardOptions.js
Add support for 'string' boolean values in case the server sends the default boolean values as string.
> Fix Switch components not getting set with the default value the first time they render CORWEB-104

- src/components/molecules/MainListItem/MainListItem.jsx
- src/components/pages/MigrationsPage/MigrationsPage.jsx
- src/components/pages/ReplicasPage/ReplicasPage.jsx
- src/sources/ReplicaSource.js
- src/stores/ReplicaStore.js
Remove 'Tasks Remaining' header in replicas list
Add 'Total Executions' header in replicas list
Greatly reduce the number of calls to the API
> Don't load replica executions for each replica CORWEB-146

- src/actions/NotificationActions.js
- src/components/molecules/NotificationDropdown/NotificationDropdown.jsx
- src/components/organisms/DetailsPageHeader/DetailsPageHeader.jsx
- src/components/organisms/Notifications/Notifications.jsx
- src/components/organisms/Notifications/NotificationsStyle.js
- src/components/organisms/PageHeader/PageHeader.jsx
- src/components/pages/WizardPage/WizardPage.jsx
- src/sources/NotificationSource.js
- src/sources/WizardSource.js
- src/stores/MigrationStore.js
- src/stores/NotificationStore.js
Some notifications are persisted in browser's local storage.
They are cleared when notification's dropdown is closed.
QA note: To see a persisted notification, create a migration
from a replica or create a migration or replica using the
wizard.
> Add persisted notifications support CORWEB-149

- src/components/atoms/EndpointLogos/test.jsx
- src/components/organisms/WizardEndpointList/test.jsx
Tests previously checked whether Providers in the Wizard which had no
Endpoints, had `Add New...` dropdown item.
The tests should check whether Providers with no Endpoints have `Add`
button.
> Fix failing tests caused by a previous feature CORWEB-153

- src/components/atoms/ReloadButton/ReloadButton.jsx
The benefits are:
- Animating the `Reload` button is consistent with animating its neighbour the `Search` button.
- Provides a feedback for clicking it.
- Doesn't allow the user to spam the button while the animation is in progress.
> Add `Reload` button animation to lists

- src/components/molecules/Modal/Modal.jsx
If the modal is opened on top of scrollable content, allow scrolling
only for the opened modal, disabling the scrollable content's scroll.
When closing the modal, restore scrolling functionality and scrolling
position to modal's parent's scrollable content.
QA note: To reproduce, go to Endpoint Details Page on a small window
open 'Edit Endpoint' modal and scroll using the mouse wheel. Before
the fix, the background of the modal (its parent) would also scroll.
> Disable background scroll if modal is open

- src/components/atoms/StatusIcon/images/progress.js
- src/components/molecules/LoadingButton/images/loading.svg
Simplify the generated SVG used for `LoginButton` and `StatusIcon`
loading animation, so that no masks are needed. The masks seem to cause
some artefacts on Safari.
Instead of masks use `circle` stroke and circle `arc` path.
> Fix SVG small loading animation on Safari

- src/components/molecules/NewItemDropdown/NewItemDropdown.jsx
- src/components/molecules/NewItemDropdown/test.jsx
- src/components/organisms/PageHeader/PageHeader.jsx
Use `a` HTML tag to redirect to new Migration or Replica, instead of
redirecting using Javascript.
This allows browser features such as right click to 'Open link in new
tab' and seeing the URL in the bottom status bar before opening it.
> Redirect to new item using HTML `a` tag

- src/actions/InstanceActions.js
- src/components/pages/WizardPage/WizardPage.jsx
- src/stores/InstanceStore.js
Instead of loading the instances when the user reaches 'Select VMs'
page, load them after user chooses the 'Source' endpoint.
Advantage: The instances may already be loaded when reaching the 'Select
VMs' page, thus decreasing the waiting time on the 'Loading' animation.
Disadvantage: The instances are requested from the server each time the
user changes the 'Source' endpoint.
> Preload wizard instances after choosing source

- src/components/organisms/ChooseProvider/ChooseProvider.jsx
- src/components/organisms/Endpoint/Endpoint.jsx
- src/components/organisms/PageHeader/PageHeader.jsx
- src/components/pages/EndpointsPage/EndpointsPage.jsx
- src/stores/ProviderStore.js
Show loading animation while providers are being loaded into
`ChooseProvider` modal.
Show loading animation while provider's connection info schema is loaded
into `Endpoint` modal.
QA note: Throttle browser's network connection speed to see it in action.
> Show loading in `ChooseProvider` and `Endpoint`

- src/components/organisms/Endpoint/Endpoint.jsx
- src/components/organisms/PageHeader/PageHeader.jsx
Show `Back` button instead of `Cancel` if the modal is opened after
`ChooseProvider` modal and switch to `ChooseProvider` modal on `Back`
button click.
> Add `Back` button to Endpoint modal

- src/components/molecules/MainListFilter/MainListFilter.jsx
To reproduce the issue before this fix, resize the browser while in one
of the lists (Replica, Migration or Endpoint) and toggle the `SelectAll`
checkbox
> Fix `MainListFilter` layout on small screens

- src/actions/WizardActions.js
- src/components/pages/WizardPage/WizardPage.jsx
- src/sources/WizardSource.js
- src/stores/WizardStore.js
Save Wizard's state as base64 to URL, so that reloading the page no
longer clears everything already set in the Wizard.
This also allows sharing URL between people with the exact same
environment.
To clear the saved state, simply remove everything from the URL's `d`
parameter and reload the page.
This is especially useful for debugging, could be disabled for
production if not needed.
This feature must be viewed as a BETA version, since there may be
issues if the encoded data is no longer available in Wizard's actual
data.
> Encode Wizard's state in URL ('Permalink' support)

- src/components/pages/EndpointDetailsPage/EndpointDetailsPage.jsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
If a modal redirects to a new page, its 'unmount' function is not
called and so window scroll is not restored.
> Restore window scroll after modal redirects

- src/components/molecules/DatetimePicker/DatetimePicker.jsx
- src/components/molecules/DatetimePicker/story.jsx
- src/components/molecules/DatetimePicker/style.js
- src/components/organisms/Schedule/Schedule.jsx
Implement ability to disable specific dates in `DateTimePicker`.
Allow only future dates to be selected in scheduler's 'Expire Date'
field.
> Disable old dates in scheduler 'Expire Date' field

- package.json
- private/storybook/webpack.config.js
- server/dev.js
- webpack.config.js
- yarn.lock
Use cleaner UI for webpack console logging when building modules using
`yarn start` or `yarn build`.
> Refactor and improve webpack logging

- webpack.config.js
Note, this does not affect `yarn install`.
> Hide deprecation warning from `yarn start\build`

- package.json
- src/components/molecules/Dropdown/Dropdown.jsx
- yarn.lock
This way the list is not cut off if it doesn't fit in the parent
container, i.e.: is inside a scrollable container.
> Render `Dropdown` list to document's body

- src/actions/EndpointActions.js
- src/actions/MigrationActions.js
- src/actions/ProjectActions.js
- src/actions/ReplicaActions.js
- src/actions/UserActions.js
- src/actions/WizardActions.js
- src/components/organisms/Endpoint/Endpoint.jsx
- src/components/pages/EndpointDetailsPage/EndpointDetailsPage.jsx
- src/components/pages/EndpointsPage/EndpointsPage.jsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/MigrationsPage/MigrationsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/components/pages/ReplicasPage/ReplicasPage.jsx
- src/components/pages/WizardPage/WizardPage.jsx
- src/stores/EndpointStore.js
Instead of relying on `Wait.for` in order to wait for an action's
response, make actions return promises and use them instead.
This allows for better performance if wait time is very long and
multiple actions are dispatched simultaneously.
> Make Actions return promises instead of `Wait.for`

- src/components/molecules/Dropdown/Dropdown.jsx
This makes the `Dropdown` unusable if there's a modal with a greater
z-index than the Dropdown's CORWEB-161
> Fix `Dropdown` list appearing behind modal CORWEB-161

- src/components/organisms/EndpointDetailsContent/EndpointDetailsContent.jsx
Before this patch, only fields containing URLs could be copied.
> Enable copying of every value in endpoint details

- src/actions/ReplicaActions.js
- src/components/organisms/ReplicaDetailsContent/ReplicaDetailsContent.jsx
- src/components/organisms/ReplicaDetailsContent/test.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/sources/ReplicaSource.js
- src/stores/ReplicaStore.js
Immediately add the 'Delete' response to the current executions and
redirect to 'Replica Executions' page.
Disable the `Delete` button if replica doesn't have any executions.
> Add 'Delete Replica Disks' button to Replica page CORWEB-157

- src/components/molecules/Modal/Modal.jsx
VS Code now comes with styled components CSS 'linting', as a result it identified an invalid CSS property.
> Remove an invalid CSS property

- src/utils/ApiCaller.js
Improves distinction between logging an API request and its response
and between API calls and other types of logging.
> Add colours to request logs

- src/sources/ReplicaSource.js
If there's only one replica in the replica list, execution sorting
would not trigger, thus replica may appear with `COMPLETED` status even
though the last execution was not successful.
> Fix execution sorting if there's only one replica

- src/components/molecules/UserDropdown/UserDropdown.jsx
The steps do reproduce the crash:
1. Log in using VPN.
2. Disconnect VPN.
3. Load replica list page.
4. Click the `UserDropdown` menu.
This means that the connection will timeout eventually, but until then,
no user is signed in, so no user info can be displayed there.
A custom message is instead displayed: 'No signed in user'.
> Fix crash when user clicks `UserDropdown` menu

- package.json
- src/components/molecules/Dropdown/Dropdown.jsx
- yarn.lock
Occasionally the dropdown list would appear to the left of its
corresponding button by a few pixels.
To reproduce this issue open a dropdown that doesn't fit in the page
(i.e. days of the month in the schedule). The dropdown list would also
snap to the correct position at the next DOM update.
> Fix dropdown list position

- src/components/molecules/Dropdown/Dropdown.jsx
This fixes the case where a dropdown is opened while its button is
scrolled out of its original position.
> Fix issue with dropdown list position

- src/components/molecules/Dropdown/Dropdown.jsx
Fixes an issue where dropdown list would appear as if the page was not
scrolled, even though the page was.
> Fix dropdown's list position when page is scrolled

- src/components/molecules/Dropdown/Dropdown.jsx
If a dropdown is opened in a modal which, in its turn, is opened on page
which is scrolled, dropdown's list position wouldn't be correct.
Because, in that case, the body's scroll is removed and it's top
property is set instead, so that the body can't be scrolled while a
modal is opened. This complicates the dropdown's list position.
> Fix rare case of dropdown's list position in modal

- src/utils/ApiCaller.js
To reproduce this issue remove CORIOLIS_URL env. variable or set it to
an invalid URL and try to login. The application would show an infinite
spinner instead of the error being handled.
> Infinite spinner for invalid server response

- src/components/molecules/TaskItem/TaskItem.jsx
This applies to 'timestamp' in execution tasks. The creation date seems
to be the same for all execution tasks, I think a better alternative is
to use the updated date so that the timestamp is more diverse. If
there's no updated date, than the creation date will be used.
> Use 'updated date' instead of 'creation date'

- src/components/organisms/Executions/index.jsx
Fix an issue where execution's status is shown instead of execution's
ID.
> Fix showing execution's status instead of ID

- src/actions/UserActions.js
- src/sources/UserSource.js
This, actually, doesn't do anything currently. It just means that if the
Keystone authorization token expiration time is increased, the UI client
will also stay authorized in that time.
Currently the Keystone token expires in 1 hour. The UI client can stay
authorized up to 30 days if the Keystone token expiration time is
increased.
This also includes a small code documentation of the UI authorization
process.
> Increase authorization token cookie expiration CORWEB-167

- src/components/pages/MigrationsPage/index.jsx
- src/components/pages/ReplicasPage/index.jsx
Rarely, when the browser is redirected from replicas page (ie due to
token expiration), the replicas polling would continue in the
background.
This PR also contains a commit which adds polling to migrations list
page, which didn't have any polling at all being done in the 
background.
> Fix replicas page polling issue in rare situation

- src/components/molecules/NotificationDropdown/index.jsx
Shown after creating a replica / migration.
> Fix 'Invalid date' label in notifications dropdown

- src/components/organisms/Endpoint/index.jsx
- src/utils/ObjectUtils.js
When creating a new endpoint, the input fields would be temporarily
cleared while the endpoint was validating.
> Fix clearing endpoint fields while validating

- src/components/molecules/SearchInput/index.jsx
When searching for a replica, migration or endpoint, don't reset the
search icon's color to grey when leaving the search input if the search
input is not empty. Thus, it is much clearer if the list items are
filtered or not.
> User primary search icon if search is not empty

- src/components/molecules/WizardOptionsField/index.jsx
- src/components/organisms/WizardOptions/index.jsx
- src/components/organisms/WizardPageContent/index.jsx
- src/components/pages/WizardPage/index.jsx
- src/config.js
- src/sources/ProviderSource.js
- src/stores/ProviderStore.js
- src/types/Endpoint.js
- src/types/Field.js
After the destination options schema is loaded, load the destination
options values which complement the schema. For example, if using the
schema we render a text input for a string field, after loading the
destination options, we may have a dropdown instead with available
values for that field and a default value selected.
> Load destination options values in wizard

- private/storybook/Decorator.jsx
- src/components/molecules/Dropdown/index.jsx
- src/components/molecules/Dropdown/story.jsx
- src/components/molecules/WizardOptionsField/index.jsx
- src/components/organisms/WizardEndpointList/index.jsx
- src/components/organisms/WizardNetworks/index.jsx
For each duplicated item in a dropdown list, display its ID value bellow
its label, this makes it much more easier to understand what's actually
selected. No changes should be seen if there're no duplicated items.
For a quick test of this feature, create an endpoint with the same name
as an existing one, go to Wizard's source or target selection page and
open the dropdown containing the duplicated endpoint names.
> Improve duplicated items in the dropdown component

- src/components/atoms/EndpointLogos/index.jsx
- src/components/pages/MigrationsPage/index.jsx
- src/components/pages/ReplicasPage/index.jsx
When showing replicas / migrations list, if a replica / migration
endpoint is missing show 'Not Found' where endpoint's logo would be.
After replicas / migrations list has loaded, if the endpoints are still
loading, endpoint logo is not available, since we don't know yet the
replica / migration's endpoint's type. Show 'Loading...' instead where
endpoint's logo would be.
> Improve endpoint status in lists using logos

- src/sources/WizardSource.js
Used when creating the network map for a replica / migration in the
wizard.
This is based on a discussion with @gabriel-samfira and @aznashwan
> Use network id instead of network name

- src/components/organisms/PageHeader/index.jsx
- src/components/pages/EndpointsPage/index.jsx
- src/components/pages/MigrationsPage/index.jsx
- src/components/pages/ReplicasPage/index.jsx
- src/stores/UserStore.js
With this, changing the project is handled in on place only, the
`PageHeader` component, instead of being handled in every place that
uses `PageHeader` component.
Also, `Wait.for` function is replaced by an improved switch project
promise, which should gain us a small performance boost while waiting
for the project to change.
> Refactor the process of switching a project

- src/components/molecules/DatetimePicker/index.jsx
- src/components/molecules/ScheduleItem/index.jsx
- src/types/Execution.js
- src/types/MainItem.js
- src/types/Task.js
- src/utils/DateUtils.js
Fixes an issue where daylight saving time may be ignored in some cases
when converting from UTC to local time due to not using the current year
when retrieving the timezone offset.
> Fix ignoring daylight saving time

- src/components/molecules/ScheduleItem/index.jsx
- src/components/organisms/Schedule/index.jsx
If a dropdown's value is changed to `any` it should have it's value
rendered in bold, just like all the other values, to indicate it is
changed.
> Fix not using bold for `any` in schedule dropdowns

- src/components/organisms/MainDetails/index.jsx
- src/components/templates/DetailsTemplate/index.jsx
- src/components/templates/MainTemplate/index.jsx
- src/components/templates/WizardTemplate/index.jsx
Resizing the wizard, the lists or the details pages to a small size
would mess up the header of the page and in the case of the details page
would also make some elements on the page inaccessible.
> Fix layout for the main templates on small screen

- src/config.js
It should stay disabled until the `destination-options` API is
available.
> Temporarily disable destination options for Azure

- src/sources/UserSource.js
- src/utils/ApiCaller.js
Occasionally, after an authorisation token expires, the app would keep
looping between the login page and the previous page spamming the user
with 'Unauthorised' notifications.
This commit also fixes the project being reset after an unauthorised API
call.
> Fix an infinite loop when having expired token

- cypress.json
- private/cypress/config.template.js
- private/cypress/integration/login/Invalid Login.js
- private/cypress/integration/migration/1 - Create Openstack Endpoint.js
- private/cypress/integration/migration/2 - Create VmWare Endpoint.js
- private/cypress/integration/migration/3 - Create VmWare Openstack Migration.js
- private/cypress/integration/migration/4 - Cancel first running migration.js
- private/cypress/integration/migration/6 - Delete first migration.js
- private/cypress/integration/migration/7 - Delete e2e Openstack endpoint.js
- private/cypress/integration/migration/8 - Delete e2e VmWare endpoint.js
- private/cypress/integration/replica/1 - Create Azure Endpoint.js
- private/cypress/integration/replica/2 - Create VmWare Endpoint.js
- private/cypress/integration/replica/3 - Create VmWare Azure Replica.js
- private/cypress/integration/replica/4 - Cancel first running replica.js
- private/cypress/integration/replica/5 - Cannot delete used endpoint.js
- private/cypress/integration/replica/6 - Delete first replica.js
- private/cypress/integration/replica/7 - Delete e2e Azure endpoint.js
- private/cypress/integration/replica/8 - Delete e2e VmWare endpoint.js
- private/cypress/integration/scheduler/Scheduler Operations.js
- private/cypress/support/commands.js
- private/cypress/support/index.js
- src/components/atoms/StatusPill/index.jsx
- src/components/organisms/DetailsContentHeader/index.jsx
Made the login process programmatically using Cypress Request API
instead of using the UI, thus allowing the tests to run sequentially
automatically instead of manually running them one after the other.
NOTE: A new parameter has been added to `private/cypress/config.js`:
`coriolisUrl`, since Cypress now needs to know the Coriolis URL in order
to be able to login with its API. The `config.template.js` has been
updated to reflect this.
> Add support for Cypress 'Run All Tests'

- cypress.json
- private/cypress/integration/migration/3 - Create VmWare Openstack Migration.js
- private/cypress/integration/replica/4 - Cancel first running replica.js
- private/cypress/integration/scheduler/Scheduler Operations.js
Wait for details page API response before clicking the Executions list
so that the executions page is not in 'Loading' state.
Also increased the timeout for an API call to be made, from 5 sec to 20
sec. The timeout for an API call response remains 30 sec.
> Wait for details page API response

- src/components/pages/MigrationsPage/index.jsx
- src/components/pages/ReplicasPage/index.jsx
If, while having replicas / migrations page opened, a new replica /
migration is created somewhere with new endpoints, the opened page would
display the created replica / migration, but it wouldn't display the new
endpoints' logo.
To solve this, the endpoints are also polled when polling replicas /
migrations.
> Refresh new endpoints in replicas/migrations page

- src/components/organisms/WizardSummary/index.jsx
Fixed the schedule's hour and minute in the wizard summary page so it
doesn't always display 'every hour, every minute' and instead displays
the correct value.
> Hour and minute not correct in wizard summary

- src/components/atoms/CopyValue/index.jsx
- src/components/atoms/DropdownButton/index.jsx
- src/components/atoms/DropdownButton/test.jsx
- src/components/molecules/DatetimePicker/index.jsx
- src/components/molecules/DatetimePicker/test.jsx
- src/components/molecules/DropdownLink/index.jsx
- src/components/molecules/DropdownLink/test.jsx
- src/components/molecules/LoginOptions/index.jsx
- src/components/molecules/LoginOptions/test.jsx
- src/components/molecules/Modal/index.jsx
- src/components/molecules/SearchInput/index.jsx
- src/components/molecules/SearchInput/test.jsx
- src/components/molecules/WizardOptionsField/index.jsx
- src/components/molecules/WizardOptionsField/test.jsx
- src/components/organisms/EndpointDetailsContent/index.jsx
- src/components/organisms/EndpointDetailsContent/test.jsx
- src/components/organisms/MainDetails/index.jsx
- src/components/organisms/MainDetails/test.jsx
- src/components/organisms/MainList/index.jsx
- src/components/organisms/MainList/test.jsx
- src/components/organisms/ReplicaDetailsContent/test.jsx
- src/components/organisms/Schedule/index.jsx
- src/components/organisms/Schedule/test.jsx
- src/components/organisms/WizardNetworks/test.jsx
- src/components/organisms/WizardSummary/index.jsx
- src/components/organisms/WizardSummary/test.jsx
The fixed tests also include a new method of testing using a
`data-test-id` attribute which allows easier component querying and a
more legible assertion: instead of something like
`div.contains('string_to_test').toBe(true)`, we can write
`(div.prop('data-test-id') === 'name').toBe('string_to_test')`.
In the future, this pattern should be applied to all the other unit
tests.
> Fix all failing unit tests

- src/components/App.jsx
- src/components/molecules/DatetimePicker/index.jsx
- src/components/molecules/ScheduleItem/index.jsx
- src/components/molecules/Table/index.jsx
- src/components/molecules/Table/story.jsx
- src/components/molecules/Timeline/index.jsx
- src/components/molecules/WizardOptionsField/index.jsx
- src/components/molecules/WizardType/index.jsx
- src/components/organisms/AssessmentDetailsContent/index.jsx
- src/components/organisms/DetailsContentHeader/index.jsx
- src/components/organisms/EndpointDetailsContent/index.jsx
- src/components/organisms/Executions/index.jsx
- src/components/organisms/MainDetails/index.jsx
- src/components/organisms/MigrationDetailsContent/index.jsx
- src/components/organisms/ReplicaDetailsContent/index.jsx
- src/components/organisms/Schedule/index.jsx
- src/components/organisms/WizardOptions/index.jsx
- src/components/organisms/WizardPageContent/index.jsx
- src/components/pages/EndpointDetailsPage/index.jsx
- src/components/styleUtils/StyleProps.js
Widen the replica, migration, endpoint, assessment detail pages and
wizard pages layout.
Previous width value was '800px', new value is '928px'.
> Widen details and wizard pages layout

- src/components/organisms/Executions/index.jsx
- src/stores/ReplicaStore.js
Fix an issue where executing a replica will not cause the newly created
execution to be automatically selected.
Technical note: store functions which modify the state should create a
new object instead of updating the old one.
> New execution is not automatically selected

- src/stores/MigrationStore.js
- src/stores/ReplicaStore.js
Fixes an issue where the replicas/migrations list loading animation is
displayed each time data is polled from the server. This issue is
reproducible only if the replicas/migrations list is empty.
> Fix list loading animation if list is empty

- src/components/molecules/DatetimePicker/index.jsx
- src/components/molecules/Dropdown/index.jsx
Fixes the `Dropdown` and `DateTimePicker` list positioning if window is
horizontally scrolled.
> Fix list pos. if window is horizontally scrolled

- private/cypress/support/index.js
Some tests depend on previous tests (i.e. creating a replica / migration
depends on creating the 2 endpoints), so it is safer to stop all the
tests after the failed one.
> Stop Cypress if a test failed

- src/stores/NotificationStore.js
Fixes an issue where if the same error is triggered multiple times, for
each error a notification is shown. Only new errors should be visible.
If the repeated error notification fades away, it can reappear again as
soon as it is triggered.
> Don't repeat the same error notifications

- src/components/molecules/DatetimePicker/index.jsx
Fixes an issue where the `DateTimePicker` component dispatches the
`change` event even if it is not actually changed.
For example, opening and closing the `DateTimePicker` in the scheduler
causes the 'Expiration Date' field to be bold.
> Fix `DateTimePicker` event if date not changed

- src/components/organisms/AlertModal/index.jsx
Fixes an issue where pressing the `Enter` key while a confirmation popup
is opened, doesn't always actually confirm.
To reproduce the issue, try deleting a schedule item by confirming with
`Enter` key.
> Fix `Enter` not working sometimes to confirm

- src/components/atoms/CopyMultilineValue/index.jsx
- src/components/organisms/MainDetails/index.jsx
Most likely caused by the `styled-components` module trying to set the
style using `data-test-id` prop. If `data-test-id` is null,
`styled-components` fails to set the component up.
> Fix `yarn build` fail

- src/components/organisms/Executions/index.jsx
- src/components/organisms/ReplicaDetailsContent/index.jsx
- src/components/pages/ReplicaDetailsPage/index.jsx
- src/stores/ReplicaStore.js
Sometimes after the wizard finished a replica configuration set with `execute_now: true`, the running execution would appear twice in replica's executions page.
Also includes 'Loading executions ...' message while executions are being loaded for the first time.
> Replica execution shown twice after wizard finish

- src/components/organisms/EndpointDetailsContent/index.jsx
The 'USED IN REPLICAS/MIGRATIONS' field found in the endpoint details
page, now contains links to each replica / migration.
> Links to replica in endpoint details page

- src/components/molecules/TaskItem/index.jsx
- src/sources/MigrationSource.js
- src/sources/ReplicaSource.js
The first progress update should also be the first one in the list,
mimicking an actual console output.
> Reverse progress updates sorting

- src/plugins/endpoint/openstack/ContentPlugin.jsx
- src/plugins/endpoint/openstack/SchemaPlugin.js
- src/types/Field.js
This is an intermediate PR to quickly solve the issue of not displaying
the fields in the 'Simple' form when v3 API is selected when creating an
Openstack endpoint.
> Add 2 more fields to Openstack API v3 simple form

- src/components/organisms/Endpoint/index.jsx
This issue may cause unexpected behaviour when creating or editing an
endpoint.
To fix it, 2 inputs for user name and password are created off-screen
which the browsers autofills invisible to the user.
> Browsers autofill passwords in endpoint popup

- src/utils/LabelDictionary.js
If the name of the field is the same as its label, a dictionary entry is
not necessary.
Common abbreviations and acronyms can also be defined:
'migr' -> 'Migration', 'api' -> 'API' respectively.
So 'migr_worker' will be labeled 'Migration Worker' and 'client_id' will
be labeled 'Client ID'.
> Remove unnecessary label phrases from dictionary

- src/components/atoms/DropdownButton/images/star.js
- src/components/atoms/DropdownButton/index.jsx
- src/components/atoms/DropdownButton/story.jsx
- src/components/molecules/Dropdown/index.jsx
- src/components/molecules/EndpointField/index.jsx
- src/components/molecules/WizardOptionsField/index.jsx
Used the 'asterisk' symbol from the `TextInput` component to mark
`Dropdown` components as required.
Until now, there was no way to identify the required fields if the
required fields were an enumeration (ex. OCI wizard options).
> Mark required dropdown fields as required

- src/components/molecules/WizardOptionsField/index.jsx
If a field has string enumerations (no objects enumerations with 'id'
and 'name), use the dictionary for their label.
> Use dictionary values for string enums

- src/components/molecules/AutocompleteDropdown/images/tip.js
- src/components/molecules/AutocompleteDropdown/index.jsx
- src/components/molecules/AutocompleteDropdown/story.jsx
If the searchable dropdown has a scroll the tip shapes appears as a
diamond. Switched to SVG to represent the tip as a triangle instead and
disable switching its background to the primary blue color if a scroll
is present.
> Fix dropdown tip issue when list has scroll

- src/components/organisms/WizardOptions/index.jsx
Wizard Options page responds to browser height by changing between one
and two columns when grouping fields.
> Make Wizard Options columns count responsive

- src/components/molecules/PropertiesTable/index.jsx
Appears when rendering for the first time OCI's 'Migration Image Map'
field in the Wizard Options page.
This error was related to the fact that the dropdown had a separator.
> Fix '[object object]' label in dropdown

- src/plugins/endpoint/default/OptionsSchemaPlugin.js
The destination environment is not set when creating a replica /
migration.
A 'return' statement was forgotten.
> Replica / Migration destination env. is not set

- src/components/atoms/StatusImage/images/error.js
- src/components/atoms/StatusImage/images/success.js
- src/components/atoms/StatusImage/index.jsx
The status images are animated when they are first shown. They can be
seen when validating an endpoint.
> Animate 'success' and 'error' status images

- src/components/organisms/Endpoint/index.jsx
- src/components/organisms/EndpointValidation/index.jsx
If the validation error message has a long line (with no spaces), the
layout wouldn't display properly. To see the effect try filling an
invalid username for an OCI endpoint.
> Fix long line layout in validation error message

- src/plugins/endpoint/default/ContentPlugin.jsx
If a textarea field is present in an endpoint modal, the following field
would not get rendered. This is the case for the OCI provider.
> Fix endpoint fields skipping in modal

- src/components/molecules/Dropdown/index.jsx
Makes the animation direction reversed between showing and hiding the
checkmark symbol in the dropdown with multiple selection component.
It now comes from left to right when it appears and from right to left
when it disappears.
> Adjust dropdown checkmark animation

- src/components/organisms/Endpoint/Endpoint.jsx
- src/components/organisms/EndpointDetailsContent/EndpointDetailsContent.jsx
- src/components/organisms/EndpointDetailsContent/test.jsx
- src/components/pages/EndpointDetailsPage/EndpointDetailsPage.jsx
- src/plugins/endpoint/default/ContentPlugin.jsx
- src/stores/EndpointStore.js
Renders the OCI's `private_key_passphrase` field as a password input in
endpoint new / edit modal and as a password value in endpoint details
page.
Also adds the ability to specify custom password field names in the
`EndpointStore` file.
If the password field names must be configurable, the array should be
moved in the config file.
> Use password for OCI `private_key_passphrase`

- src/components/organisms/WizardOptions/WizardOptions.jsx
When the wizard options are rendered for the first time the tooltips are
not shown when hovering over the question mark symbol (as seen in
advanced Azure options at the Linux Migration Image field).
> Fix tooltip not showing the first time

- private/cypress/integration/4 - migrations and replicas/VmWare -> Azure Replica/3 - Delete replica.js
- private/cypress/integration/6 - users and projects/1 - Create a project.js
- private/cypress/integration/6 - users and projects/2 - Add a new user as a member.js
- private/cypress/integration/6 - users and projects/3 - Add existing user as a member.js
- private/cypress/integration/6 - users and projects/4 - Create a user.js
- private/cypress/integration/6 - users and projects/5 - Edit and delete user.js
- private/cypress/integration/6 - users and projects/6 - Edit and delete project.js
- private/cypress/support/commands.js
- src/components/molecules/AutocompleteDropdown/AutocompleteDropdown.jsx
- src/components/molecules/DropdownLink/DropdownLink.jsx
- src/components/molecules/EndpointField/EndpointField.jsx
- src/components/molecules/ProjectListItem/ProjectListItem.jsx
- src/components/molecules/UserListItem/UserListItem.jsx
- src/components/organisms/ProjectDetailsContent/ProjectDetailsContent.jsx
- src/components/organisms/ProjectMemberModal/ProjectMemberModal.jsx
- src/components/pages/ProjectDetailsPage/ProjectDetailsPage.jsx
- src/sources/ProjectSource.js
- src/stores/ProjectStore.js
The tests are run only if users and projects management is enabled in
the `src/config.js` file.
This commit also fixes an issue where removing a user with multiple
roles from a project (from the project details page) may cause the user
to still be a member of that project (visible only after a page refresh).
> Create e2e tests for users and projects management

- src/components/organisms/DetailsPageHeader/DetailsPageHeader.jsx
- src/components/organisms/DetailsPageHeader/test.jsx
- src/components/pages/AssessmentsPage/AssessmentsPage.jsx
- src/sources/AssessmentSource.js
- src/sources/AzureSource.js
- src/sources/EndpointSource.js
- src/sources/InstanceSource.js
- src/sources/MigrationSource.js
- src/sources/NetworkSource.js
- src/sources/NotificationSource.js
- src/sources/ProviderSource.js
- src/sources/ReplicaSource.js
- src/sources/ScheduleSource.js
- src/sources/UserSource.js
- src/sources/WizardSource.js
- src/stores/AzureStore.js
- src/utils/ApiCaller.js
**Remove redundant `Promise` wrapper from API calls**
The 'axios' API Caller returns a promise so it is no longer necessary to
wrap the API calls with a `Promise`.
This also includes using `Promise.all` when depending on multiple API
call responses.
**Remove cookie dependencies from all 'Source' files**
Project ID is no longer retrieved from cookies in all 'Source' files,
instead it is retrieved from the API Caller class, which now handles the
retrieval of project ID from cookies. This allows having one place where
cookie retrieval and validation happens.
Includes an update to a unit test.
> Refactor 'Source' classes

- package.json
- private/cypress/integration/0 - cleanup/Cleanup.js
- private/cypress/support/commands.js
- yarn.lock
The cleanup will appear as a regular test (so that it can also be
easily run manually and cleanup errors can be seen nicely) and will
delete all the replicas, migrations, endpoints, users created by Cypress
and projects created by Cypress.
The cleanup will happen only if the current user is 'cypress'.
Also includes and updated version of Cypress: 3.0.1 -> 3.0.2.
> Run a cleanup command before running tests

- package.json
- private/cypress/integration/4 - migrations and replicas/VmWare -> Azure Replica/2 - Scheduler Operations.js
- src/components/organisms/Schedule/Schedule.jsx
- yarn.lock
Using `moment-timezone` module we can get the local timezone label
abbreviation (ex.: EET, EEST, PST).
> Use local timezone label in schedule component

- src/components/molecules/TaskItem/TaskItem.jsx
This applies to the progress updates found in execution's tasks. If the
task is not running, dim all its progress updates.
> Dim all but the last task's progress updates

- src/components/pages/WizardPage/WizardPage.jsx
Fixes an issue where switching between different wizard page
configurations (using different saved data permalink bookmarks) does not
update the wizard page data, so a browser refresh was needed every time.
> Fix wizard page not updating after URL change

- src/components/organisms/WizardPageContent/WizardPageContent.jsx
There may be a case where an object field may have its "properties" as a
non-array type. So instead of testing the length of that properties
field we can test the availability of the "filter" function.
> Fix crash in Wizard's options page

- src/components/organisms/PageHeader/PageHeader.jsx
- src/sources/NotificationSource.js
- src/types/NotificationItem.js
The seen notifications are now tied to a project id, so switching to a
new project no longer clears all the previously seen ones.
The notifications are now refreshed as soon as the project is switched,
so we don't have to wait for the 5 seconds poll timer after switching.
> Add project switching support to notifications

- src/components/molecules/WizardOptionsField/WizardOptionsField.jsx
- src/utils/LabelDictionary.js
Enum values should not be transformed by the dictionary in order to be
displayed.
There's a new property in the dictionary which holds all the enum fields
which are an exception to this rule (currently there's only one such
field: 'port_reuse_policy', which means that the enums of this field
will be transformed by the dictionary).
> Don't use the label dictionary for all enum values

- src/components/molecules/WizardOptionsField/WizardOptionsField.jsx
If the field is an enum with an empty array, don't render a dropdown
with an empty list, instead render a text input.
> Fix options field rendering of empty 'enum' array

- server/proxy.js
- src/components/atoms/Switch/Switch.jsx
- src/components/molecules/AutocompleteDropdown/AutocompleteDropdown.jsx
- src/components/molecules/Dropdown/Dropdown.jsx
- src/components/molecules/ScheduleItem/ScheduleItem.jsx
- src/components/molecules/WizardOptionsField/test.jsx
- src/components/organisms/AssessmentDetailsContent/AssessmentDetailsContent.jsx
- src/components/organisms/ReplicaExecutionOptions/ReplicaExecutionOptions.jsx
- src/components/organisms/Schedule/Schedule.jsx
- src/components/organisms/WizardPageContent/WizardPageContent.jsx
- src/components/organisms/WizardSummary/WizardSummary.jsx
- src/components/pages/WizardPage/WizardPage.jsx
- src/plugins/endpoint/default/OptionsSchemaPlugin.js
- src/sources/AssessmentSource.js
- src/sources/ProjectSource.js
- src/sources/ReplicaSource.js
- src/sources/ScheduleSource.js
- src/sources/UserSource.js
- src/sources/WizardSource.js
- src/stores/ScheduleStore.js
- src/utils/ObjectUtils.js
In Javascript there's no need to check for both `null` and `undefined`
if the equality operator (`==`) is used instead of the identity operator
(`===`).
The rule (according to default 'eslint' and 'flow' specs) is that the
`===` operator should always be used with one exception, which is when
checking for `null` / `undefined` since `== null` will only coerce a
value to null only if the value is null or undefined.
> Refactor all `null` / `undefined` checks

- src/plugins/endpoint/azure/ConnectionSchemaPlugin.js
- src/plugins/endpoint/azure/ContentPlugin.jsx
The Azure endpoint creation / edit modal now has a simple / advanced
toggle. If 'simple' is selected, only required fields are shown.
> Group Azure endpoint fields by their required prop

- src/config.js
Note: If the API is not enabled, an error notification will be displayed.
> Enable Oracle VM Server destination options call

- src/components/organisms/PageHeader/PageHeader.jsx
- src/components/pages/EndpointsPage/EndpointsPage.jsx
- src/components/pages/WizardPage/WizardPage.jsx
If an endpoint's connection info is not valid, the endpoint is no longer
deleted when clicking on Cancel / Back button.
> Disable endpoint auto-deletion on creation cancel

- src/plugins/endpoint/azure/ConnectionSchemaPlugin.js
- src/plugins/endpoint/azure/ContentPlugin.jsx
'Subscription ID' is now a required field.
'Tenant' is a dynamically required field: it is required only for
'CustomCloud' cloud profile and for 'Service Principal Credentials'
login method.
Fixes an issue where 'Tenant' is not visible in 'CustomCloud' cloud
profile.
'CustomCloud' fields are now sorted: the required fields are first, then
the fields are sorted alphabetically.
> Improve Azure endpoint fields rendering UX

- src/components/pages/WizardPage/WizardPage.jsx
This issue only applies to providers which have destination options API
calls with additional parameters (see config.js, currently Azure and
OCI).
If the destination options API doesn't return the expected values for
the env. required fields (i.e. missing "enum" property for the
"envRequiredFields" fields specified in config.js), the UI may keep
making requests on every character typed in those fields.
> Handle invalid response from dest. options API

- src/plugins/endpoint/default/OptionsSchemaPlugin.js
If there's no data for the 'migration_image_map' field, the field is
completely removed instead of just being empty.
> Fix empty 'migration_image_map' body

- src/components/organisms/MainDetails/MainDetails.jsx
- src/components/organisms/MainDetails/test.jsx
- src/components/organisms/MigrationDetailsContent/MigrationDetailsContent.jsx
- src/components/organisms/ReplicaDetailsContent/ReplicaDetailsContent.jsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/stores/InstanceStore.js
The structure or existence of the 'info' field in a replica or a
migration can't be trusted. An alternative method is used to retrieve
the VM instances connected to a specific network, which involves making
an API call for each instance of a replica or a migration.
This affects only the replica and migration details page and the
following changes are visible:
- a 'Loading...' label is display in the 'Connected VMs' field of the
network table while the migration / replica instances details are
loading.
- an error message may be shown if there are issues retrieving the
instances details.
> Remove references to API's migration 'info' field

- src/components/pages/AssessmentDetailsPage/AssessmentDetailsPage.jsx
- src/components/pages/WizardPage/WizardPage.jsx
- src/sources/AssessmentSource.js
- src/sources/WizardSource.js
- src/stores/MigrationStore.js
- src/types/NotificationItem.js
Persisted notification are no longer a thing, so the code pertaining to
that is no longer needed.
Previously a regular notification could be made 'persisted', using
`persist: true` option, by saving it and displaying it in 'Bell'
component dropdown.
Currently, the 'Bell' component dropdown displays a different set of
predefined notifications.
> Remove unused code from previous notification sys.

- src/utils/LabelDictionary.js
All AzureStack's 'suffix' properties should now have 'Suffix' keyword
added to their labels.
> Add 'Suffix' keyword to all Azure suffix props.

- src/components/molecules/AssessedVmListItem/AssessedVmListItem.jsx
- src/components/organisms/AssessmentDetailsContent/AssessmentDetailsContent.jsx
- src/components/pages/AssessmentDetailsPage/AssessmentDetailsPage.jsx
- src/types/Assessment.js
Use VMWare's machine id to match VMs between VMWare and Azure.
Previously, VM path was used.
> Improve Azure Migrate VM matching

- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
Previously, a new migration details page would not load if visited from
the notifications dropdown, while currently on another migration details
page. Same issue applied to the replica details page.
> Fix issue with switching pages from notifications

- server/proxy.js
- src/components/organisms/Notifications/style.js
- src/stores/AzureStore.js
If the Azure endpoint doesn't have valid credentials, show a clearer
message and cancel subsequent requests to Azure services.
Previously, only the subsequent's request error message was displayed,
the login error was ignored by UI.
> Use clearer Azure Migrate invalid auth. message

- src/sources/InstanceSource.js
- src/stores/InstanceStore.js
- src/utils/ApiCaller.js
Previously, if a user typed in the instances search input while the
instances were loading from a previous search, unexpected results may
have appeared. Usually the response from the previous search came before
the current search, in which case UI elements were updated incorrectly
for a short time. Rarely, the previous search response came after the
current search, in which case the instances list from the previous
search were displayed instead.
With this patch, typing while still searching is fully supported by
canceling all the previous requests (thus, bandwidth is also improved).
> Improve wizard instances searching

- src/components/molecules/Dropdown/Dropdown.jsx
If a dropdown item has no label, the value is used.
If it also has no value, an empty string is used.
Previously if it had no label and no value `[object Object]` was
displayed.
> Show empty string if dropdown item value is empty

- src/components/atoms/InfoIcon/InfoIcon.jsx
- src/components/atoms/SmallLoading/SmallLoading.jsx
- src/components/atoms/SmallLoading/package.json
- src/components/atoms/SmallLoading/story.jsx
- src/components/molecules/AssessedVmListItem/AssessedVmListItem.jsx
- src/components/molecules/AssessmentListItem/AssessmentListItem.jsx
- src/components/molecules/EndpointField/EndpointField.jsx
- src/components/molecules/Table/Table.jsx
- src/components/molecules/WizardOptionsField/WizardOptionsField.jsx
- src/components/organisms/AssessmentDetailsContent/AssessmentDetailsContent.jsx
- src/components/organisms/AssessmentMigrationOptions/AssessmentMigrationOptions.jsx
- src/components/pages/AssessmentDetailsPage/AssessmentDetailsPage.jsx
- src/components/pages/AssessmentsPage/AssessmentsPage.jsx
- src/sources/AssessmentSource.js
- src/sources/EndpointSource.js
- src/stores/AssessmentStore.js
- src/stores/AzureStore.js
- src/stores/InstanceStore.js
- src/stores/NetworkStore.js
- src/stores/ProviderStore.js
- src/types/Assessment.js
- webpack.config.js
Implement editable target endpoint, location and resource group.
Store all the newly updated-able fields locally so there are the same
every time the assessment is loaded.
Includes logic to make sure the VM sizes are compatible with target
endpoint.
Add total machines label to assessment list item.
Store instances and networks in `localStorage` for a faster page load
if the source endpoint has been used previously.
Clicking the bottom `Refresh` button forces data to be loaded from the
server instead of loading it locally.
Add migration options to azure migrate popup.
Update the assessment loading animations.
Allow the use of endpoints without barbican secret.
Don't show canceled requests as errors in production.
> Make assessment data editable and store it locally

- src/plugins/endpoint/azure/ConnectionSchemaPlugin.js
Usually the value of a field is not send to the server if the field has
a default value and the user didn't set a value. We need to send the
default value for Azure even if the user didn't change it in the UI.
> Send default `cloud_profile` on Azure creation

- src/components/organisms/MainDetails/MainDetails.jsx
- src/sources/NotificationSource.js
The name of a notification item should be the same name used to name
replicas and migrations: the name of the first instance. Previously the
concatenation of all instances names was used for notification item
name.
> Use the first instance as notification item name

- src/components/organisms/MainDetails/MainDetails.jsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/sources/InstanceSource.js
- src/stores/InstanceStore.js
If the instance is not found in order to display the 'Connected VMs' in
network mapping, don't show a notification popup 'Instance Not Found'
error, instead show a clearer message in the 'Connected VMs' column.
> Don't show instance not found in replica page

- src/sources/NotificationSource.js
- src/utils/ApiCaller.js
The notifications polling floods the logs (`console.log`) and makes it
difficult to track other requests.
> Skip notifications data polling logs

- .eslintrc
- src/components/atoms/CopyMultilineValue/CopyMultilineValue.jsx
- src/components/atoms/CopyMultilineValue/test.jsx
- src/components/organisms/EndpointDetailsContent/EndpointDetailsContent.jsx
- src/components/organisms/MainDetails/MainDetails.jsx
- src/components/organisms/MainDetails/test.jsx
- src/components/organisms/WizardSummary/test.jsx
When there are multiple instances in a replica / migration, show each
instance in a separate line, instead of listing them comma-separated for
a much better reading experience.
The layout is also kept when copying to clipboard.
The same layout is also applied to the list of migrations / replicas
where an endpoint is used (in the endpoint details page).
> Improve layout of instances list

- webpack.config.js
This will allow the user to see the original file name and the source
code line number in the case of a Javascript error when using browser's
developer tools.
Note that the full source code can also be enabled in the developer
tools if needed by changing `nosources-source-map` to `source-map` in
`webpack.config` before building.
> Use a javascript source map for production builds

- src/components/organisms/MainDetails/MainDetails.jsx
- src/components/organisms/MainDetails/test.jsx
The text was accidentally reverted (back to '-') when a previous merge
conflict was resolved.
A unit test for this case is also included.
> Add missing text when source instance is not found

- src/components/molecules/Dropdown/Dropdown.jsx
- src/components/molecules/Dropdown/story.jsx
Split the dropdown list item label on multiple rows if label doesn't fit
in a single row.
Previously, the label was split on multiple rows but only if it
contained multiple words. For example 'A very long label item' would get
multiple rows with no issues, but 'averylonglabelitem' would cause
layout issues.
So, this affects, for example, items with long IDs as labels (see OCI
provider).
> Fix dropdown labels layout if label is too long

- src/components/molecules/EndpointField/EndpointField.jsx
- src/components/organisms/Endpoint/Endpoint.jsx
- src/plugins/endpoint/default/ContentPlugin.jsx
Currently in use by vsphere and oraclevm 'Port' field.
What this means is that a number is sent to the API instead of a string
and the UI text input allows only numbers as input.
Also includes 'Fix missing field in connection info modal' commit:
A field may be missing in providers without a connection info plugin if
the number of fields is not an odd number.
> Add integer support to connection info

- src/components/pages/WizardPage/WizardPage.jsx
- src/stores/WizardStore.js
If a migration can't be created don't redirect to user, instead
re-enable the Finish / Next button, while displaying the error message.
> Handle migration creation fail in Wizard

- src/components/atoms/Arrow/Arrow.jsx
- src/components/atoms/Arrow/images/arrow-thick.js
- src/components/atoms/Arrow/images/arrow.js
- src/components/atoms/HorizontalLoading/HorizontalLoading.jsx
- src/components/atoms/HorizontalLoading/package.json
- src/components/atoms/HorizontalLoading/story.jsx
- src/components/organisms/WizardInstances/WizardInstances.jsx
- src/components/organisms/WizardInstances/test.jsx
- src/components/organisms/WizardPageContent/WizardPageContent.jsx
- src/components/pages/AssessmentDetailsPage/AssessmentDetailsPage.jsx
- src/components/pages/WizardPage/WizardPage.jsx
- src/config.js
- src/sources/InstanceSource.js
- src/stores/InstanceStore.js
Instead of loading a new page of instances on next page click, load all
pages in the background one after one.
Searching is done on the server only if the instances are not completely
loaded in the background.
The UI shows the number of currently loaded pages and indicates whether
all pages have been completely loaded.
> Load instances in chunks in the background

- src/components/atoms/Arrow/images/arrow-thick.js
- src/components/atoms/Arrow/images/arrow.js
- src/components/organisms/WizardInstances/test.jsx
- src/components/pages/WizardPage/WizardPage.jsx
- src/config.js
- src/stores/InstanceStore.js
Resizing and zooming affects the number of instances shown per page in
Wizard Instances selection page.
The minimum and maximum instances per page is configurable in
`config.js` at the `instancesPerPage:` line.
> Show instances per page based on window height

- src/components/organisms/DetailsContentHeader/DetailsContentHeader.jsx
If the replica name is very long (its first instance name), the 'Execute
Now' button would get pushed out of its allocated space.
> Fix replica details name layout for long name

- src/components/organisms/WizardSummary/WizardSummary.jsx
- src/components/organisms/WizardSummary/test.jsx
Displays blue 'Coriolis Migration' label in wizard summary page.
Shows UTC when displaying time in the Schedule section of the wizard
summary page.
> Update Wizard Summary page labels

- src/components/molecules/MainDetailsTable/MainDetailsTable.jsx
- src/components/organisms/MainDetails/MainDetails.jsx
- src/components/organisms/ReplicaDetailsContent/ReplicaDetailsContent.jsx
- src/components/pages/AssessmentDetailsPage/AssessmentDetailsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/sources/NetworkSource.js
- src/stores/NetworkStore.js
Previously a network ID was shown instead.
This is done by retrieving the destination endpoint's networks and
matching them with replica's network mapping.
> Show network name in Replica details mapping

- src/components/organisms/MainDetails/MainDetails.jsx
The 'Last Updated' field should be visible in all migration details
pages.
> Fix missing 'Last Updated' in Migration page

- src/components/organisms/Endpoint/Endpoint.jsx
- src/config.js
- src/plugins/endpoint/openstack/ConnectionSchemaPlugin.js
- src/plugins/endpoint/openstack/ContentPlugin.jsx
- src/sources/EndpointSource.js
- src/sources/Schemas.js
- src/utils/LabelDictionary.js
The switch appears when creating or editing an Openstack endpoint if the
option is enabled in `config.js` (`showOpenstackCurrentUserSwitch`).
If the switch is toggled an empty `connection_string` is sent to the
API.
> Shows 'Use Current for Authentication' switch

- src/components/organisms/WizardInstances/WizardInstances.jsx
- src/components/organisms/WizardInstances/test.jsx
- src/components/organisms/WizardPageContent/WizardPageContent.jsx
- src/components/pages/WizardPage/WizardPage.jsx
- src/config.js
- src/sources/InstanceSource.js
- src/stores/InstanceStore.js
Some providers may prefer listing all instances at once ('OVM'), some
providers may prefer listing more instances than what fits in one UI
page, while other providers prefer listing as few instances as possible.
This is now supported and configurable in
`config.js`:`instancesListBackgroundLoading`. Check the comments of that
line for how the configuration works.
> Dynamic instances pagination based on provider

- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/organisms/WizardOptions/WizardOptions.jsx
- src/components/organisms/WizardSummary/WizardSummary.jsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/plugins/endpoint/default/OptionsSchemaPlugin.js
- src/sources/MigrationSource.js
- src/sources/WizardSource.js
- src/stores/MigrationStore.js
- src/types/WizardData.js
Options like target env, network and storage mappings can be updated
when recreating the migration.
> Add ability to recreate a migration CORWEB-179

- src/components/organisms/LoginForm/LoginForm.jsx
- src/components/organisms/LoginForm/test.jsx
- src/components/pages/LoginPage/LoginPage.jsx
- src/config.js
- src/sources/UserSource.js
- src/stores/UserStore.js
- src/types/User.js
The user domain input can be toggled on / off in config file.
The last user domain used is saved in local storage, after a successful
login. This means you can disable the input anytime after the first
login.
A default value is used the first time the user loads the page.
> Allow option to type user domain on login page CORWEB-188

- src/components/atoms/TextInput/TextInput.jsx
The line height issues were mostly visible on Safari. The input cursor's
height was inconsistent when focusing or typing in a text input.
> Fix `line-height` issues for `TextInput` CORWEB-193

- src/sources/EndpointSource.js
When duplicating an endpoint, secrets were never used.
> Fix 'Duplicate Endpoint' not using secrets

- src/components/molecules/TaskItem/TaskItem.jsx
Instead of highlighting the last task, the first one was highlighted
when an execution was running.
> Fix highlighting of last execution task CORWEB-198

- package.json
- src/components/organisms/MainList/MainList.jsx
A random number appears at the bottom of replicas, migrations and
endpoints list, caused by adding the schedule icon tooltip feature.
> Fix random number appearing when loading main list

- package.json
- src/components/atoms/Switch/Switch.jsx
Switch inputs are now focusable and can be toggled using SPACE key.
> Focus switch inputs using TAB key CORWEB-199

- src/components/organisms/EditReplica/EditReplica.jsx
If there are a lot of fields in the Target Options (ex.: Openstack), the
scroll doesn't show up correctly on Chrome and Firefox.
> Fix `Edit Replica` modal not scrolling correctly

- src/plugins/endpoint/default/ConnectionSchemaPlugin.js
- src/stores/ProviderStore.js
The object fields should now render even though they don't have values
from the destination options API call.
This happens, for example, when editing an Openstack replica and its
dest-options call is disabled in `config.js`.
> Render object fields with no dest options values

- src/stores/NetworkStore.js
While new networks are loaded for new Wizard Options, old networks are
still displayed in the Wizard Networks list.
> Fix networks refresh delay in Wizard Networks page

- src/components/organisms/Endpoint/Endpoint.jsx
- src/sources/EndpointSource.js
- src/stores/EndpointStore.js
When updating or adding a new endpoint, its Barbican secret may not be
active immediately.
A polling is made to make sure the secret is active. If after 10 retries
(2 second waiting period after each request) the secret is still
inactive, the secret payload call gets rejected.
> Add support for non-active secret when updating

- src/components/organisms/MainDetails/MainDetails.jsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/stores/MigrationStore.js
- src/types/MainItem.js
When recreating a migration, recreate it from the original replica, if
the migration was originally created from a replica.
Show the Create Migration from Replica modal if that's the case.
The Migration Details page displays a link to the original replica,
if it has one.
> Recreate migration from replica CORWEB-202

- src/components/organisms/WizardNetworks/WizardNetworks.jsx
- src/components/organisms/WizardStorage/WizardStorage.jsx
If there are more than 10 items in the Networks Wizard Page or in the
Storage Wizard Page, change the input from Dropdown to
AutocompleteDropdown.
> Dynamically change the networks to autocomplete CORWEB-207

- src/components/molecules/WizardOptionsField/WizardOptionsField.jsx
- src/components/organisms/WizardOptions/WizardOptions.jsx
Use 'Separate Replica/VM' if wizard type is replica and 'Migration' if
wizard type is migration.
> Dynamically change 'Separate / VM' label CORWEB-206

- package.json
- src/components/App.jsx
- src/components/atoms/Tooltip/Tooltip.jsx
- src/components/organisms/AssessmentDetailsContent/AssessmentDetailsContent.jsx
- src/components/organisms/AssessmentMigrationOptions/AssessmentMigrationOptions.jsx
- src/components/organisms/Endpoint/Endpoint.jsx
- src/components/organisms/EndpointDuplicateOptions/EndpointDuplicateOptions.jsx
- src/components/organisms/MainList/MainList.jsx
- src/components/organisms/WizardOptions/WizardOptions.jsx
- yarn.lock
Tooltip wouldn't show if is required in certain conditions. For example,
it wouldn't show if is inside Endpoint modal, especially difficult for
it to show up after changing tabs from 'Simple' to 'Advanced'.
> Fix tooltips not always showing up

- private/storybook/Decorator.jsx
- src/components/molecules/TaskItem/TaskItem.jsx
- src/components/organisms/ProjectMemberModal/ProjectMemberModal.jsx
Progress text in execution's task gets outside of panel bounds if the
text has a very long word like a long error ID.
> Fix progress text getting outside of panel bounds

- src/components/molecules/MainDetailsTable/MainDetailsTable.jsx
MAC address is shown as the accordion header instead of Network Name in
Replica Details Page.
> Switch network name with MAC address in details

- src/sources/ReplicaSource.js
This is consistent with the Wizard replica / migration creation and
Migration Edit.
> Use network id instead of name on Replica Edit

- package.json
- src/components/molecules/MainDetailsTable/test.jsx
- yarn.lock
Fix Jest's dependency (handlebars lib) vulnerability by upgrading it to
a newer version.
Includes a small test fail fix.
> Fix Jest's dependency vulnerability

- config.js
- src/components/atoms/DropdownButton/DropdownButton.jsx
- src/components/molecules/PropertiesTable/PropertiesTable.jsx
- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/organisms/WizardPageContent/WizardPageContent.jsx
- src/components/pages/AssessmentDetailsPage/AssessmentDetailsPage.jsx
- src/components/pages/WizardPage/WizardPage.jsx
- src/plugins/endpoint/default/OptionsSchemaPlugin.js
- src/sources/ProviderSource.js
- src/stores/ProviderStore.js
- src/types/Config.js
- src/types/Endpoint.js
AWS supports source options schema and now it also supports
'source-options' API calls to populate the source options schema with
available values, similar to 'destination-options' API calls available
to other providers.
To add to the list of providers which support the 'source-options' API,
update the `sourceProvidersWithExtraOptions` property in `./config.js`
file.
> Add 'source-options' API support

- package.json
- yarn.lock
`ms-rest-azure` uses `request` module, the `request` module is not
found if not installed locally in `node_modules`.
> Add 'request' module as a dependency

- src/components/molecules/Panel/Panel.jsx
- src/components/molecules/Panel/story.jsx
- src/components/molecules/Panel/test.jsx
- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/stores/InstanceStore.js
- src/stores/NetworkStore.js
- src/stores/ProviderStore.js
Edit Replica modal uses improved caching (caches more data) and data can
now be reloaded using a button.
> Add cache refresh support to Edit Replica modal

- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/constants.js
- src/types/Providers.js
- src/utils/ObjectUtils.js
Replica editing is disabled if target provider doesn't support replica
update.
> Disable editing if provider doesn't support it

- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
Sometimes polling wouldn't get cleared after going from Details page to
another Details page, so the new Details page would show info from a
wrong page.
> Fix polling not clearing on Details pages

- src/components/organisms/EditReplica/EditReplica.jsx
- src/sources/ReplicaSource.js
Storage mapping update would fail, if other options are also updated.
Show default storage option in target options tab.
Re-enable update button if update request fails.
> Fix storage-mapping update schema fail

- src/components/molecules/PropertiesTable/PropertiesTable.jsx
- src/components/molecules/WizardOptionsField/WizardOptionsField.jsx
- src/utils/LabelDictionary.js
The AWS source options should look a little better since the
PropertiesTable labels are shorter.
Remove the PropertiesTable required symbols from Edit Replica modal,
visible for Azure target endpoint.
> Fix Edit Replica modal layout issues

- src/components/organisms/FilterList/FilterList.jsx
The filter group for Replicas, Migrations etc. list pages didn't work
properly. A second click was needed to actually filter the list by the
selected item.
> Fix list filter group not working

- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/organisms/WizardOptions/WizardOptions.jsx
- src/components/organisms/WizardPageContent/WizardPageContent.jsx
- src/components/organisms/WizardStorage/WizardStorage.jsx
- src/components/organisms/WizardSummary/WizardSummary.jsx
- src/plugins/endpoint/default/OptionsSchemaPlugin.js
- src/sources/ReplicaSource.js
- src/stores/EndpointStore.js
- src/stores/ReplicaStore.js
- src/stores/WizardStore.js
Auto select the server's storage config default in 'Default Storage'
field, found in Wizard target options and Edit Replica target options.
When creating a replica, don't send any storage mapping data to the
server, if its target mapping is 'Default'.
When editing a replica, if a target storage mapping is changed to
'Default', send the 'Default Storage' as the target mapping.
In Wizard Summary page, show only the storage mappings that are actually
sent to the server.
> Update storage mapping default behaviour

- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/constants.js
The Coriolis `constants.py` has been updated: a replica should be
editable if both the target and the source provider have update
capabilities.
> Update the "is replica editable" function

- src/components/organisms/WizardSummary/WizardSummary.jsx
- src/plugins/endpoint/default/OptionsSchemaPlugin.js
If a text field is an empty string, skip it completely, don't send it at
all to the server. This also applies to object type fields which have text
fields as properties.
The change is also reflected in Wizard Summary page.
> Skip empty string fields when creating replica

- src/components/atoms/AutocompleteInput/AutocompleteInput.jsx
- src/components/atoms/AutocompleteInput/images/arrow.js
- src/components/molecules/AutocompleteDropdown/AutocompleteDropdown.jsx
- src/components/molecules/PropertiesTable/PropertiesTable.jsx
If there are a lot of items in migration image map, use an embedded
autocomplete component instead of dropdown.
> Embed Autocomplete component in migration image

- config.js
- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/pages/WizardPage/WizardPage.jsx
- src/constants.js
- src/stores/ProviderStore.js
- src/types/Config.js
Dynamically detect if a provider can make `destination-options` or
`source-options` API calls to fill the destination / source options
schema. For this, we use Coriolis API's `constants.py` info.
Previously, the list of providers which support these calls was stored
in `config.js`. Note that we still need to store the providers which can
make additional destination / source API calls with a set of field
values, in the config file.
> Dynamically detect if a provider has env options

- src/components/organisms/WizardOptions/WizardOptions.jsx
If the field name contains 'password' keyword, set its type to password.
> Auto set wizard options field to password CORWEB-213

- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/organisms/WizardOptions/WizardOptions.jsx
The Endpoint modal inputs style is now used in Edit Replica modal,
instead of the Wizard Options inputs style.
> Update Edit Replica modal inputs style

- src/components/pages/AboutModal/AboutModal.jsx
- src/components/pages/AssessmentsPage/AssessmentsPage.jsx
- src/components/pages/EndpointsPage/EndpointsPage.jsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/MigrationsPage/MigrationsPage.jsx
- src/components/pages/ProjectsPage/ProjectsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/components/pages/ReplicasPage/ReplicasPage.jsx
- src/components/pages/UsersPage/UsersPage.jsx
- src/sources/AzureSource.js
- src/sources/EndpointSource.js
- src/sources/MigrationSource.js
- src/sources/ProjectSource.js
- src/sources/ReplicaSource.js
- src/sources/UserSource.js
- src/stores/AzureStore.js
- src/stores/EndpointStore.js
- src/stores/LicenceStore.js
- src/stores/MigrationStore.js
- src/stores/ProjectStore.js
- src/stores/ReplicaStore.js
- src/stores/UserStore.js
- src/utils/ApiCaller.js
- src/utils/ApiLogger.js
The downloadable log now contains extra information:
- The window location (the URL relative path) from which the API request
was made
- The JS stack of the API request (the functions initiating the request)
Polling requests are now ignored in the downloadable log and in the
developer’s tools log, to avoid logs pollution.
> Improve API requests logging

- src/components/molecules/PropertiesTable/PropertiesTable.jsx
- src/components/organisms/Endpoint/Endpoint.jsx
- src/plugins/endpoint/default/OptionsSchemaPlugin.js
- src/plugins/endpoint/index.js
- src/plugins/endpoint/ovm/OptionsSchemaPlugin.js
- src/sources/Schemas.js
- src/types/Field.js
Use UI object table component in Wizard Options to render OVM
`migr_template_username_map` and `migr_template_password_map` fields.
The fields for `migr_template_password_map` are also shown as password
fields.
> Create OVM plugin to handle `migr_template` fields

- src/components/molecules/ActionDropdown/ActionDropdown.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
Show a message informing the user that editing the replica is disabled
because one of the providers doesn't support editing.
> Show tooltip if edit replica button is disabled

- config.js
Instead of loading in chunks of 10, the default for the other providers.
> Load all instances for 'hyper-v' provider

- src/components/organisms/ProjectDetailsContent/ProjectDetailsContent.jsx
- src/components/pages/ProjectDetailsPage/ProjectDetailsPage.jsx
- src/components/pages/ProjectsPage/ProjectsPage.jsx
- src/sources/ProjectSource.js
- src/sources/UserSource.js
- src/types/Project.js
The UI crashes in Projects Page if there's a role whose scope is not a
project, i.e. a system role.
> Fix a crash in Projects Page caused by roles

- src/components/molecules/AutocompleteDropdown/AutocompleteDropdown.jsx
- src/components/molecules/Dropdown/Dropdown.jsx
- src/components/molecules/MainDetailsTable/MainDetailsTable.jsx
- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/organisms/MainDetails/MainDetails.jsx
- src/components/organisms/WizardNetworks/WizardNetworks.jsx
- src/components/organisms/WizardPageContent/WizardPageContent.jsx
- src/components/organisms/WizardSummary/WizardSummary.jsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/components/pages/WizardPage/WizardPage.jsx
- src/plugins/endpoint/default/OptionsSchemaPlugin.js
- src/sources/NetworkSource.js
- src/sources/ReplicaSource.js
- src/types/MainItem.js
- src/types/Network.js
- src/utils/LabelDictionary.js
OCI supports security groups selection for each network mapping.
This affects all the places in which network mapping is used: Wizard
Networks, Edit Replica and Recreate Migration.
> Add security groups selection to network mapping

- config.js
A new OCI options field is required before making extra destination
options calls.
> Add new field to OCI's dest. options fields

- config.js
- src/components/molecules/Dropdown/Dropdown.jsx
- src/components/molecules/FieldInput/FieldInput.jsx
- src/components/molecules/MainDetailsTable/MainDetailsTable.jsx
- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/organisms/MainDetails/MainDetails.jsx
- src/components/organisms/WizardInstances/WizardInstances.jsx
- src/components/organisms/WizardNetworks/WizardNetworks.jsx
- src/components/organisms/WizardOptions/WizardOptions.jsx
- src/components/organisms/WizardPageContent/WizardPageContent.jsx
- src/components/organisms/WizardStorage/WizardStorage.jsx
- src/components/pages/AssessmentDetailsPage/AssessmentDetailsPage.jsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/components/pages/WizardPage/WizardPage.jsx
- src/sources/InstanceSource.js
- src/sources/ProviderSource.js
- src/sources/WizardSource.js
- src/stores/InstanceStore.js
- src/stores/ProviderStore.js
- src/types/Config.js
- src/types/Instance.js
Added new providers to the list of providers which support source
options: aws, openstack, azure.
Send the source options when listing an endpoint's instances.
Use `name` instead of `instance_name`, if an endpoint's instance doesn't
have the `instance_name` field.
> Improve Replica / Migration source options support

- src/plugins/endpoint/default/OptionsSchemaPlugin.js
Use the config default when setting the endpoint's options switches
after calling source / destination options.
> Add boolean config default support

- src/components/organisms/EditReplica/EditReplica.jsx
- src/sources/InstanceSource.js
- src/sources/NetworkSource.js
- src/sources/ProviderSource.js
- src/stores/InstanceStore.js
- src/stores/NetworkStore.js
- src/stores/ProviderStore.js
- src/types/Cache.js
- src/utils/ApiCaller.js
- src/utils/Cacher.js
There's now only one place where API calls are cached in the source code
and in the local storage.
A 15 minute default caching age is used for all cached API calls.
If a call is loaded from cache, a `console.log` appears stating that.
> Refactor and improve API calls caching process

- src/components/pages/WizardPage/WizardPage.jsx
The wizard shouldn't check if a user has permissions for an endpoint.
If it's listed by the API, it has the permissions.
> Remove permissions check from wizard

- config.js
- src/components/organisms/Endpoint/Endpoint.jsx
- src/components/organisms/EndpointDetailsContent/EndpointDetailsContent.jsx
- src/components/organisms/WizardOptions/WizardOptions.jsx
- src/components/pages/EndpointDetailsPage/EndpointDetailsPage.jsx
- src/plugins/endpoint/azure/ContentPlugin.jsx
- src/plugins/endpoint/default/ContentPlugin.jsx
- src/plugins/endpoint/openstack/ContentPlugin.jsx
- src/stores/EndpointStore.js
- src/types/Config.js
You can now use the `config.js` to specify a list of password fields,
which will be used to rendered inputs as password inputs. Applicable to
options and endpoints fields.
If an option or endpoint field contains the 'password' keyword, the
fields will be rendered as password by default (no need to add it to the
config list).
> Use a configurable list of password fields

- src/components/organisms/WizardStorage/WizardStorage.jsx
If the disk name has more than 3 sub paths (see Azure), show only the
last 3 and truncate the rest.
Applicable to Wizard Storage page.
If the name is truncated, a browser tooltip shows the full name.
> Truncate disk name sub paths in Wizard Storage

- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/organisms/WizardOptions/WizardOptions.jsx
- src/components/organisms/WizardPageContent/WizardPageContent.jsx
- src/components/pages/AssessmentDetailsPage/AssessmentDetailsPage.jsx
- src/sources/ProviderSource.js
- src/stores/ProviderStore.js
The first time the options are loading, show the loading animation for
the entire page.
For subsequent options loading, show disabled loading for all fields
except for the fields which are required in `env` parameter of the
options calls.
This means that while the options are being loaded, users can still
change those fields, in which case, the previous options call is
canceled and a one is started.
> Improve options loading UX

- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/stores/MigrationStore.js
Sometimes (slow connection) missing endpoint is show in replica /
migration details page, while the page is still being loaded.
> Fix details pg. sometimes showing missing endpoint

- src/plugins/endpoint/default/ConnectionSchemaPlugin.js
- src/sources/Schemas.js
Most schemas come from the API with `oneOf` as their root property.
However, some schemas (ex.: VMWare's source schema) don't have `oneOf`,
but instead may have schema properties directly in the root.
> Add support for schemas without `oneOf` as root

- src/stores/MigrationStore.js
- src/stores/ReplicaStore.js
When going from migration details page to migrations list page, the
migrations list page would briefly display an older status of the
migration from the details page.
> Fix sync issues when going from details to list

- src/components/molecules/Dropdown/Dropdown.jsx
- src/components/organisms/WizardNetworks/WizardNetworks.jsx
Includes an update to dropdown's multiple selection that fixes a bug
(checkmark wouldn't disappear) that occurred when the maximum is reached.
> Limit security groups selection to a maximum of 5

- .github/workflows/nodeci-master.yml
- .github/workflows/nodeci-pr.yml
- README.md
Configured two workflows, one used for the PRs and a second one called `Master` for the final merge commits. The `Master` workflow status badge is also used in the README file.
> Added Nodejs testing workflow

- .gitignore
- .vscode/settings.json
These VSCode settings allow using the node modules version of Flow and
disables VSCode's Typescript validation (interferes with Flow's
validation).
> Add Flow VSCode settings

- src/sources/Schemas.js
The 'Azure' provider has schema definitions which are used to render
object fields. This fixes an issue where those definitions wouldn't get
parsed.
> Fix schema definitions support CORWEB-218

- src/components/organisms/WizardOptions/WizardOptions.jsx
Wizard options gets collapsed when temporary migration options field
group is shown.
> Fix a Safari CSS error

- src/components/organisms/WizardStorage/WizardStorage.jsx
Applies `word-break: break-word;` CSS style to the storage name, thus
breaking its name into multiple lines if it doesn't fit into one.
> Break storage name into lines if it is too long

- src/components/molecules/NotificationDropdown/NotificationDropdown.jsx
If the notification item's name is too long, break it on the next line,
so it doesn't overflow the items list.
> Break notification item name if it doesn't fit CORWEB-219

- src/components/organisms/MainDetails/MainDetails.jsx
- src/components/organisms/MigrationDetailsContent/MigrationDetailsContent.jsx
- src/components/organisms/ReplicaDetailsContent/ReplicaDetailsContent.jsx
- src/components/organisms/WizardPageContent/WizardPageContent.jsx
- src/components/organisms/WizardSummary/WizardSummary.jsx
- src/components/organisms/WizardSummary/test.jsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/sources/ProviderSource.js
- src/stores/ProviderStore.js
- src/types/Field.js
- src/types/MainItem.js
- src/utils/ApiCaller.js
- src/utils/Cacher.js
Options names are shown in Wizard Summary page and in Replica /
Migration Details pages, where only the IDs were displayed previously.
For the Wizard Summary page, no extra calls are necessary to display the
option names instead of IDs. For the Replica / Migration Details page,
an extra API call is required, although the call's response is cached
for 15 minutes.
A small loading icon is displayed in the Replica / Migration Details
page, next to the 'Properties' label, while the options names are being
loaded.
> Display options names instead of IDs

- src/components/molecules/MainDetailsTable/MainDetailsTable.jsx
- src/components/molecules/Panel/Panel.jsx
- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/organisms/MigrationDetailsContent/MigrationDetailsContent.jsx
- src/components/organisms/ReplicaDetailsContent/ReplicaDetailsContent.jsx
- src/components/organisms/WizardNetworks/WizardNetworks.jsx
- src/components/organisms/WizardStorage/WizardStorage.jsx
- src/stores/ProviderStore.js
If source endpoint is down, source options editing is disabled, network
and storage mapping can still be updated, but the source info is
retrieved from replica mapping.
> Allow replica update even if source is down

- src/components/organisms/WizardPageContent/WizardPageContent.jsx
- src/components/pages/WizardPage/WizardPage.jsx
- src/utils/Cacher.js
The wizard options API calls (schemas, options etc.) are cached by the
UI for 30 minutes.
A button is available to reload the data from the API along with a
message informing the user about the possibility of the data being
cached by the UI.
> Cache wizard options calls with reload ability

- src/components/pages/LoginPage/LoginPage.jsx
- src/utils/ApiCaller.js
If a user is logged out due to session expiration, if he logs right back
in, he will be redirected to the page he was on just before he was
logged out.
The information of the previous page / state he was on, is stored in the
URL itself.
> Restore previous URL path after session expiration

- src/components/organisms/WizardOptions/WizardOptions.jsx
Allow integer fields to get render if they don't have a minimum and a
maximum value.
> Render field integers even without min and max

- src/components/atoms/StatusIcon/StatusIcon.jsx
- src/components/atoms/StatusPill/StatusPill.jsx
'ERROR' icon and 'DEBUG' label is used to represent the
'CANCELED_FOR_DEBUGGING' status.
> Add support for 'CANCELED_FOR_DEBUGGING' status

- src/components/organisms/EditReplica/EditReplica.jsx
- src/stores/ProviderStore.js
Fixes an issue where destination options would not load if Edit Replica
is opened while destination options call is already made in Replica
Details Page.
> Improve Edit Replica options loading

- src/components/molecules/FieldInput/FieldInput.jsx
- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/organisms/ReplicaMigrationOptions/ReplicaMigrationOptions.jsx
- src/components/organisms/WizardOptions/WizardOptions.jsx
- src/components/organisms/WizardOptions/test.jsx
- src/components/organisms/WizardPageContent/WizardPageContent.jsx
- src/components/organisms/WizardSummary/WizardSummary.jsx
- src/components/pages/AssessmentDetailsPage/AssessmentDetailsPage.jsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/components/pages/WizardPage/WizardPage.jsx
- src/constants.js
- src/plugins/endpoint/default/OptionsSchemaPlugin.js
- src/sources/MigrationSource.js
- src/sources/ProviderSource.js
- src/sources/WizardSource.js
- src/stores/ProviderStore.js
Removes migration type from providers, use replica type instead for all
provider schema calls.
Adds 'Replication Count' and 'Shutdown Instances' fields to migration
options.
> Add support for Replicas-as-Migrations API feature CORWEB-222

- src/components/pages/WizardPage/WizardPage.jsx
- src/sources/WizardSource.js
- src/stores/WizardStore.js
Reloading / Reopening of a Wizard page URL data link now fully supports
complex options (destination, source options API calls). Previously,
destination and source options API calls would not get made after page
reload.
Schedule and storage mapping is now also saved in URL data link.
Changing the Wizard type (i.e.: from Replica to Migration) now gets
properly reflected in the URL.
> Improve Wizard page reload state preservation

- src/components/organisms/Notifications/Notifications.jsx
- src/stores/NotificationStore.js
- src/utils/ApiCaller.js
- Truncates URLs if they are too long (truncates them to 100 chars.)
- Limits the number of notification popups to 3
This also lays the groundwork for a new feature allowing users to click
a button on a notification popup to view it in more detail.
> Improve notification popups

- src/components/organisms/WizardPageContent/WizardPageContent.jsx
- src/components/pages/AssessmentDetailsPage/AssessmentDetailsPage.jsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/components/pages/WizardPage/WizardPage.jsx
- src/constants.js
- src/sources/InstanceSource.js
- src/sources/NetworkSource.js
- src/stores/InstanceStore.js
- src/stores/NetworkStore.js
The calls made for Instances and Networks pages in the Wizard are now
cached for 30 minutes.
Cache can be refreshed in both pages using their refresh buttons.
> Cache Wizard Instances and Wizard Networks calls

- src/components/organisms/MainDetails/MainDetails.jsx
If a Replica has a password field in its `destination_environment`
property (ex.: `migr_template_password`), cover it using the
`PasswordValue` component.
> Cover password fields in Replica Details body

- src/components/atoms/CopyMultilineValue/CopyMultilineValue.jsx
- src/components/organisms/Notifications/Notifications.jsx
- src/components/organisms/Notifications/style.js
- src/types/NotificationItem.js
- src/utils/ApiCaller.js
- src/utils/DomUtils.js
API errors can now be viewed in more detail after clicking the 'View
more details' button in notifications.
Such errors are no longer auto dismissed, the user must interact with
(click anywhere inside) the API error notification item in order for
them to be dismissed.
> Add notifications view error details button

- src/components/molecules/FieldInput/FieldInput.jsx
Fields of type array should not use label dictionary for their values,
consistent with other type of fields that are represented with a
dropdown (i.e. type 'string' with 'enum' property).
> Fix array type fields using label dictionary

- src/components/App.jsx
- src/components/pages/DashboardPage/DashboardPage.jsx
- src/components/pages/NotFoundPage/NotFoundPage.jsx
- src/constants.js
- src/stores/UserStore.js
- src/types/User.js
Improve the loading UX when the user goes directly to an admin page
(ex.: `/projects`):
- Show 'Checking permissions...' message while waiting for the API to
confirm or deny the user's access to the page.
- Show 'User doesn't have permissions to view this page' message if
that's the case.
Previously, a simple 'Not Found' message has been shown instead.
Fixes some instances where 'Not Found' message was shown when going
directly to an admin page, even if the user had permissions to that page.
> Improve and fix admin pages loading UX

- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/ProjectDetailsPage/ProjectDetailsPage.jsx
- src/stores/MigrationStore.js
Some error alerts don't display server error details, because they are
custom handled with a custom message.
Fixed by handling them s using the default error handling system, thus
always displaying the full server error details.
> Fix missing info in server error alerts

- src/stores/LogStore.js
Fixes a memory leak caused by not reinitialising the JS array object
when adding new lines to the stream after the stream maximum lines have
been reached.
> Fix a log streaming memory leak

- config.js
- src/stores/ProviderStore.js
- src/types/Config.js
Previously, you could specify a list of providers for which an extra
source or destination options is made, as long as the `requiredFields`
have any value set before making the API calls.
Now, you can specify a set of required values for those fields, before
making the calls.
**Openstack example:**
Previously, `source-options` API call would have been made if
`replica_export_mechanism` had any value chosen from the list of values.
With this change, the API call is made only if `replica_export_mechanism`
is `swift_backups`, `ceph_backups` or `coriolis_backups`.
This is configurable in `./config.js`
> Add support for required values for extra options

- src/components/organisms/WizardStorage/WizardStorage.jsx
- src/components/pages/AssessmentDetailsPage/AssessmentDetailsPage.jsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/components/pages/WizardPage/WizardPage.jsx
- src/plugins/endpoint/default/InstanceInfoPlugin.js
- src/plugins/endpoint/index.js
- src/plugins/endpoint/oci/InstanceInfoPlugin.js
- src/sources/InstanceSource.js
- src/stores/InstanceStore.js
An instance info parsing plugin was developed to handle OCI's special
case where the first disk returned in the instance info is the root
disk, which can't be mapped.
> Disable disk mapping for OCI's root disk

- src/sources/InstanceSource.js
- src/stores/InstanceStore.js
This fixes a regression bug introduced by using the plugin system for
disabling OCI's root disk mapping.
> Fix issue with creating migrations from replicas

- config.js
- src/components/atoms/Pagination/Pagination.jsx
- src/components/atoms/Pagination/package.json
- src/components/organisms/FilterList/FilterList.jsx
- src/components/organisms/WizardInstances/WizardInstances.jsx
- src/types/Config.js
All main lists (replicas, migrations, endpoints, users, projects) now
display pagination control IF the number of items exceeds a configurable
amount.
The configurable amount of items per page can be modified at
`mainListItemsPerPage` in [`config.js`](config.js).
> Add pagination to lists (replicas, endpoints etc)

- src/components/organisms/Navigation/Navigation.jsx
- src/components/styleUtils/StyleProps.js
- src/components/templates/MainTemplate/MainTemplate.jsx
Reduces main navigation pages pading (Dashboard, Replicas, Endpoints
etc.) when dealing with small screens, i.e. width < 1350px.
> Reduce layout padding for small screens

- src/components/pages/AboutModal/AboutModal.jsx
- src/components/pages/LogsPage/DownloadsContent.jsx
- src/components/pages/LogsPage/LogsPage.jsx
Download Web Requests button is moved from the About Modal to the Logs
page.
Also, it and the diagnostics download link are separated from the other
logs by a horizontal separator line.
> Move download web requests button from About Modal

- src/components/molecules/MainDetailsTable/MainDetailsTable.jsx
- src/components/organisms/WizardStorage/WizardStorage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/plugins/endpoint/oci/InstanceInfoPlugin.js
- src/types/Instance.js
The message show in replica details page is a bit longer as it contains
an explanation.
This same message is now also available in the Wizard Storage screen in
the form of a tooltip next to the previous shorter variant of the
message.
> Show OCI root disk message in replica details page

- src/components/organisms/ReplicaMigrationOptions/ReplicaMigrationOptions.jsx
Display tooltip description texts for all 3 options for creating a
migration from a replica.
> Add migration options tooltip description texts CORWEB-226

- src/components/organisms/ReplicaMigrationOptions/ReplicaMigrationOptions.jsx
- src/utils/LabelDictionary.js
This way, the migration options in the wizard also benefit from the
description tooltips.
> Add migration options description to dictionary

- src/components/pages/LogsPage/DownloadsContent.jsx
- src/components/pages/LogsPage/LogsPage.jsx
- src/stores/LogStore.js
Disables clicking repeatedly on diagnostics log download button by
showing a loading animation instead of the regular download button.
> Show loading while generating diagnostics log

- src/components/atoms/AutocompleteInput/AutocompleteInput.jsx
- src/components/atoms/Checkbox/Checkbox.jsx
- src/components/atoms/DropdownButton/DropdownButton.jsx
- src/components/atoms/Pagination/Pagination.jsx
- src/components/atoms/RadioInput/RadioInput.jsx
- src/components/atoms/RadioInput/test.jsx
- src/components/atoms/Stepper/Stepper.jsx
- src/components/atoms/Switch/Switch.jsx
- src/components/atoms/TextInput/TextInput.jsx
- src/components/atoms/ToggleButtonBar/ToggleButtonBar.jsx
- src/components/molecules/AutocompleteDropdown/AutocompleteDropdown.jsx
- src/components/molecules/Dropdown/Dropdown.jsx
- src/components/molecules/FieldInput/FieldInput.jsx
- src/components/organisms/WizardInstances/WizardInstances.jsx
- src/components/organisms/WizardOptions/story.jsx
- src/utils/KeyboardManager.js
You can now using "Tab" to navigate through all field components (text
inputs, dropdowns, switches, numeric steppers etc.).
When navigating over a dropdown you can use the "Up" and "Down" arrow
keys followed by "Enter" or "Space" to select items.
You can use "Up" and "Down" arrow keys to select values for the numeric
stepper.
> Add fields keyboard navigation support

- src/sources/WizardSource.js
- src/utils/DomUtils.js
If there's a filled-in password field in the Wizard, Safari prompts the
user to store it in keychain every time any input is changed, due to the
Wizard's URL changing on each input change.
As a temporary workaround, the Wizard URL no longer changes for Safari,
meaning the Wizard page can no longer be refreshed while keeping all the
filled values and can no longer be bookmarked.
> Fix Safari password save prompt issue in Wizard

- src/sources/UserSource.js
This will allow both "admin" and "Admin" to be detected by the UI as
admin roles.
> Make admin role name test case insensitive

- src/plugins/endpoint/azure/ContentPlugin.jsx
- src/plugins/endpoint/default/ContentPlugin.jsx
- src/plugins/endpoint/openstack/ContentPlugin.jsx
Fixes an issue where no labels were shown when showing the new endpoint
modal.
> Fix missing labels when creating a new endpoint

- src/components/molecules/MainListItem/MainListItem.jsx
- src/components/organisms/DetailsContentHeader/DetailsContentHeader.jsx
If a replica or migration has more instances, the title is combined by
the name of the first instance followed by (+x more), where x is the
total number of other instances.
Previously, the title was the name of only the first instance.
> Add (+x more) to replicas title for more instances

- src/components/organisms/Executions/Executions.jsx
- src/components/organisms/ReplicaDetailsContent/ReplicaDetailsContent.jsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/sources/MigrationSource.js
- src/sources/ReplicaSource.js
- src/stores/MigrationStore.js
- src/stores/ReplicaStore.js
If a replica execution (or migration) is in 'CANCELLING' state, a
'Force Cancel' option will be presented. This will send the`force: true`
message to the API.
> Add replica and migration force cancel support CORWEB-228

- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/organisms/ReplicaMigrationOptions/ReplicaMigrationOptions.jsx
- src/components/organisms/ReplicaMigrationOptions/test.jsx
- src/components/organisms/WizardOptions/WizardOptions.jsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/sources/MigrationSource.js
- src/stores/MigrationStore.js
The `skip_os_morphing` field is now shown when recreating a migration
created from scratch.
The default value of the skip os morphing field is deduced by finding a
migration task of type 'OS_MORPHING'.
This default value is used for recreating a migration created from
scratch and for recreating a migration created from a replica.
> Preserve skip_os_morphing when recreating migr. CORWEB-229

- src/components/molecules/Panel/Panel.jsx
- src/components/molecules/Panel/story.jsx
- src/components/molecules/Panel/test.jsx
- src/components/organisms/EditReplica/EditReplica.jsx
When showing 'Recreate Replica from Migration' modal, use the correct
reload button label instead of showing 'Reload All Replica Options'.
> Use correct reload options label for migration CORWEB-230

- src/components/organisms/Endpoint/Endpoint.jsx
Fixes an issue where required fields where skipped when sending endpoint
creation data to the API, if the required fields had default values.
> Fix endpoint required default field being skipped CORWEB-233

- src/components/molecules/Dropdown/Dropdown.jsx
After clicking items in a multiple selection dropdown, it would no
longer close.
> Fix dropdown not closing when multi-selecting mode

- config.js
- server/api/ConfigApi.js
- server/main.js
- src/components/App.jsx
- src/constants.js
- src/sources/AssessmentSource.js
- src/sources/EndpointSource.js
- src/sources/InstanceSource.js
- src/sources/LincenceSource.js
- src/sources/MigrationSource.js
- src/sources/NetworkSource.js
- src/sources/NotificationSource.js
- src/sources/ProjectSource.js
- src/sources/ProviderSource.js
- src/sources/ReplicaSource.js
- src/sources/ScheduleSource.js
- src/sources/UserSource.js
- src/sources/WizardSource.js
- src/stores/LogStore.js
- src/types/Config.js
- ui-mod-sample.json
Using the UI mod JSON file (set using MOD_JSON env. variable), services
URLs can be modified.
You can use "{BASE_URL}" as a part of the service URL and it will be set
at runtime to the value of CORIOLIS_URL env. variable.
You can check [`ui-mod-sample.json`](ui-mod-sample.json) for an example
on how to modify the services URLs. The example uses the default values
used when no modding is applied.
When modding, you can add just the services URLs which you'd like to
change (there's no need to add them all, if there are URLs which use the
default value).
> Add ability to set services URLs using MOD_JSON

- .flowconfig
- src/components/organisms/EditReplica/EditReplica.jsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/stores/ProviderStore.js
Fixes an issues where, for some providers, the API may not return the
values for fields sent in a previous dest. / source options call.
For example, when requesting destination options for Azure, while
sending the location and resource group as parameters, the list of
locations and resource groups are no longer returned. As opposed to
making the destination options call for Azure the first time, with no
parameters, in which case, the list of locations and resource groups are
returned.
This means that 2 calls must be made each time to retrieve the full list
of options.
> Fix some dest. / source options values missing

- .flowconfig
- src/plugins/endpoint/default/OptionsSchemaPlugin.js
- src/plugins/endpoint/ovm/OptionsSchemaPlugin.js
When editing a replica, send the migration full image map body, even if
only one OS image map was updated.
> Send full migration image map body when updating

- .flowconfig
- .vscode/settings.json
- src/components/App.jsx
- src/components/organisms/EditReplica/EditReplica.jsx
- src/sources/MigrationSource.js
- src/stores/MigrationStore.js
- src/types/MainItem.js
Previously, if replication count value was already set when clicking
Recreate Migration, the value would appear in the Recreate Migration
modal, but it wouldn't have been sent to the API. You had to set it
again in order for it to be sent.
This fixes the issue.
> Use correct replication count when recreat. migr. CORWEB-234

- src/components/atoms/PasswordValue/PasswordValue.jsx
- src/components/molecules/MainDetailsTable/MainDetailsTable.jsx
- src/components/organisms/MainDetails/MainDetails.jsx
- src/components/organisms/MigrationDetailsContent/MigrationDetailsContent.jsx
- src/components/organisms/ReplicaDetailsContent/ReplicaDetailsContent.jsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.jsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/types/Field.js
Replica and migration details page now displays source properties
information.
Previously, only target properties information was displayed.
> Add source properties info to replica details page

- config.js
- src/stores/ProviderStore.js
If `list_all_destination_networks` is toggled, call
'destination-options' API.
> Call options for `list_all_destination_networks` CO-167

- src/components/pages/WizardPage/WizardPage.jsx
- src/sources/WizardSource.js
- src/stores/WizardStore.js
- src/types/NotificationItem.js
Now, when creating multiple replicas / migrations, there's a graceful
handling of creation errors.
Along with the error messages for each failed replica creation, a
summary alert is also shown with the total number of created and failed
replicas.
If there's at least 1 error, the user is no longer redirected from the
Wizard page.
> Better handling of multi. replicas creation errors CORWEB-232

- src/components/molecules/DeleteReplicaModal/DeleteReplicaModal.jsx
- src/components/molecules/DeleteReplicaModal/package.json
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.jsx
- src/components/pages/ReplicasPage/ReplicasPage.jsx
- src/stores/ReplicaStore.js
- src/types/Execution.js
When deleting a replica, the confirmation alert shows whether the
replica has replica disks.
If the replica has replica disks, an option to delete those disks is
presented.
The same flow is kept when deleting multiple replicas. In this case,
'delete replica disks' is executed just for the replicas which actually
have replica disks and not for all the selected replicas.
> Check for replica disks when deleting a replica CORWEB-235

- src/components/organisms/EndpointDuplicateOptions/EndpointDuplicateOptions.jsx
- src/components/organisms/ProjectMemberModal/ProjectMemberModal.jsx
- src/components/organisms/ProjectModal/ProjectModal.jsx
- src/components/organisms/UserModal/UserModal.jsx
New Project, New User, Duplicate Endpoint and Add Project Member modals
had no labels for their inputs.
This is a regression bug caused by commit "Add dictionary support for
fields with same name" 1293baca57e29d7199622b209dd897c97861fdaf
> Fix missing labels in some modals

- src/components/pages/WizardPage/WizardPage.jsx
- src/stores/WizardStore.js
When using the wizard, after the source or destination schema is loaded,
or after the source or destination options are loaded, set the current
value of the fields to their corresponding default values, if those
fields don't already have a value.
In the case of fields with enums, don't set their value to the default
value if the default value can't be found in the list.
> Fill wizard data current value with default value

- src/sources/ReplicaSource.js
When having multiple RUNNING tasks, sorting may not be properly done for
the first replica in the list of replicas.
> Fix some instances where tasks are not sorted

- src/sources/MigrationSource.js
- src/sources/NotificationSource.js
- src/sources/ReplicaSource.js
- src/stores/LogStore.js
The '/details' path component is redundant as it sends the same output
as skipping it when listing replicas or migrations.
> Remove the '/details' path component

- src/components/organisms/ProjectMemberModal/ProjectMemberModal.jsx
Almost all missing labels were added in commit
83787392042d23956e2ea4fbe6625092bf9160d1.
But, some were missed in the New User tab of the Add Member to Project
modal.
> Add some missing labels in Project Member modal

- src/components/App.jsx
When loading an admin page (Projects, Users, Users Details etc.) by
browser refresh (F5), the page might have been stuck at "Checking
Permissions...". Going to those pages from the Coriolis UI main menu
worked as expected.
> Fix page load stuck at "Checking Permissions..."

- src/stores/ProviderStore.ts
This is a regression bug cause by ad5e96adf15bbfb64010c489871f54609e915e51.
This commit improves on the method used to associate a request response
to its corresponding emitter. Initially proposed by commit ad5e96adf15bbfb64010c489871f54609e915e51.
> Fix source options hanging in Recreate Migration

- src/components/molecules/Panel/Panel.tsx
- src/components/molecules/Panel/images/loading.svg
- src/components/organisms/EditReplica/EditReplica.tsx
This disables the update button when editing a replica and the create
button when recreating a migration while options (source, destination,
network and storage) are being loaded.
Previously, the button would be disabled only if the user was on the
options panel for which the options was currently being loaded.
There's also now a loading indicator for each of the 4 panels, so the
user is informed which panel is still waiting for its options.
> Disable update / create while options are loading CORWEB-239

- src/components/organisms/ReplicaMigrationOptions/ReplicaMigrationOptions.tsx
- src/components/organisms/ReplicaMigrationOptions/replicaMigrationFields.ts
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.tsx
- src/components/pages/MigrationsPage/MigrationsPage.tsx
- src/sources/MigrationSource.ts
- src/stores/MigrationStore.ts
Migrations can now be recreated in bulk in the Migrations List page.
If a migration has 'replica_id', then the Create Migration from Replica
default fields are used.
If a migration is a 'regular' migration (created using the Wizard), the
original fields are used.
> Recreate migrations in bulk in migrations list CORWEB-238

- config.ts
- src/@types/Config.ts
- src/sources/UserSource.ts
The name of the admin role is now configurable. As a reminder, the admin
role name is used to check if a user is allowed to do certain admin
operations (Projects, Users pages among others).
> Make the admin role name configurable

- src/components/organisms/WizardOptions/WizardOptions.tsx
In Wizard Options, boolean switches didn't have "Not Set" as an option.
> Fix an issue where "Not Set" was not an option CO-176

- src/components/pages/LogsPage/DownloadsContent.tsx
Since times in the app are displayed in local time (replica / migration
info, tasks, schedule etc.), a notice is displayed for Logs page where
times are displayed in UTC.
> Add notice about using UTC time in Logs page CO-176

- src/components/organisms/WizardSummary/WizardSummary.tsx
'shutdown_instances' displayed incorrect default value in Wizard Summary
page when left untouched.
> Fix incorrect boolean values in Wizard Summary

- src/components/pages/LogsPage/DownloadsContent.tsx
Small text change indicating that download logs start and end times are
not necessarily in UTC.
> Download logs notice text change

- src/components/organisms/WizardSummary/WizardSummary.tsx
The app may crash at Wizard Summary page when creating a new replica /
migration, if setting a dropdown field to null.
> Fix a crash when setting a property to null

- .vscode/launch.json
- README.md
Using the provided launch configuration, a Chrome instance is launched
against the localhost dev server and debugging is enabled in VS Code.
Further instructions about the client and node server debugging is added
in the README.md file.
> Add ability to debug the project from VS Code

- src/plugins/endpoint/default/OptionsSchemaPlugin.ts
- src/sources/MigrationSource.ts
- src/sources/ReplicaSource.ts
This applies to Editing a replica, Recreating a migration or Creating a
migration from a replica
> Add ability to unset minion pool mappings

- src/components/organisms/EditReplica/EditReplica.tsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.tsx
When Editing a replica, recreating a migration or migrating from a
replica, the instance OSMorphing Minion pool mappings are shown for
both platforms, source and destination, instead of showing only the
destination platform minion pools.
> Fix OSMorphing minions shown for wrong platform

- src/components/molecules/Dropdown/Dropdown.tsx
Fixes an issue where the time between mouse button down and up had to be
less than 100ms. Time was increased to 1s.
The timing is required in order to be able to open the dropdown list
when the dropdown button is focused using the TAB key.
> Fix dropdown click not registering correctly

- src/components/molecules/NotificationDropdown/NotificationDropdown.tsx
If a replica or a migration was running and the user clicked the bell
notification item for it, the URL path would include an extra '/'
character.
> Remove extra '/' from notification dropdown path

- .vscode/launch.json
- src/components/molecules/PropertiesTable/PropertiesTable.tsx
Horizontal scroll appears in Wizard Options when showing field of type
'Properties Table', like the 'Execute Now Options' field.
Also, includes ability to attach the vscode debugger to an already
running Chrome process.
> Fix scroll show in field of type properties table

- src/@types/Field.ts
- src/components/organisms/EditReplica/EditReplica.tsx
- src/components/organisms/MainDetails/MainDetails.tsx
- src/components/organisms/MinionPoolDetailsContent/MinionPoolMainDetails.tsx
- src/components/organisms/WizardSummary/WizardSummary.tsx
- src/plugins/endpoint/default/OptionsSchemaPlugin.ts
- src/plugins/endpoint/openstack/OptionsSchemaPlugin.ts
- src/plugins/endpoint/ovm/OptionsSchemaPlugin.ts
The 'migr_image_map' field now only uses 'linux' and 'windows' as
sub-properties instead of 'linux_os_image' and 'windows_os_image'.
Previously, only Openstack used the field without the '_os_image'
suffix.
> Remove '_os_image' suffix from migr. image fields

- package.json
- src/@types/Field.ts
- src/@types/declarations.d.ts
- src/components/molecules/FieldInput/FieldInput.tsx
- src/components/molecules/PropertiesTable/PropertiesTable.tsx
- src/components/organisms/WizardOptions/WizardOptions.tsx
- yarn.lock
This issue is visible when changing the Openstack source 'Replica
Transfer Mechanism' field, which causes other fields to appear /
disappear, which is confusing, especially since the layout of the fields
also changes from vertical to horizontal.
As a UX hot fix, the layout of the options will always be horizontal and
a small animation will highlight the appearance of new fields.
> Fix Options fields changing in a confusing way

- src/components/atoms/Tooltip/Tooltip.tsx
Sometimes the tooltip (the bubble shown when hovering over (?) help
icon), if there's no space available, can't be shown in its default
place (to the right of the help icon) and another place (like the top of
the help icon) is chosen.
In that case, the tooltip's pointing arrow would be black and in the
wrong position.
This commit fixes this CSS issue.
> Fix tooltip's CSS when not in default position

- src/components/organisms/WizardPageContent/WizardPageContent.tsx
- src/components/pages/WizardPage/WizardPage.tsx
While the first set of options from 'destination-options' API call are
being loaded, a big Loading animation is displayed.
While the second set of options are being loaded, if the user is on
'Simple' tab, he may not notice them loading and thus may not know why
the 'Next' button is disabled.
This commit fixes this issue by display a 'Loading ...' animated button
while the second set of options are being loaded, instead of the
disabled 'Next' button.
> Show loading button in Wizard Options

- src/plugins/endpoint/default/ConnectionSchemaPlugin.ts
The Coriolis Regions field is no longer required. It also now includes a
tooltip description.
> Make Coriolis Regions field non-required

- src/plugins/endpoint/openstack/ConnectionSchemaPlugin.ts
The CEPH options fields weren't rendered correctly when creating a new
Openstack endpoint.
The CEPH options weren't displayed when editing an Openstack endpoint
with CEPH options.
> Fix CEPH options not working properly

- .vscode/launch.json
- .vscode/settings.json
- src/components/organisms/DashboardContent/modules/ActivityModule/ActivityModule.tsx
If a replica or a migration was running and the user clicked the recent
activity notification item for it, the URL path would include an extra
'/' character.
> Remove extra '/' from dashboard activity path CORWEB-245

- src/plugins/endpoint/default/ConnectionSchemaPlugin.ts
In some situations, after editing an endpoint, secrets were no longer
used to store the endpoint's connection info.
> Fix an issue where secrets were no longer used

- src/components/organisms/WizardOptions/WizardOptions.tsx
- src/components/pages/WizardPage/WizardPage.tsx
Fixes an issue where some fields in wizard options page may appear, in
some circumstances, in the wrong column, leaving an empty space where it
should actually be.
Fixes an issue where the Next button would show "Loading", when options
were loading, but the user presses the back button and is no longer in
the options page.
> Fix small UI/UX issues in Wizard Options page

- package.json
- src/components/pages/AssessmentDetailsPage/AssessmentDetailsPage.tsx
- src/components/pages/AssessmentsPage/AssessmentsPage.tsx
- src/sources/AzureSource.ts
- src/sources/EndpointSource.ts
- src/sources/InstanceSource.ts
- src/sources/NetworkSource.ts
- src/sources/ProviderSource.ts
- src/sources/WizardSource.ts
- src/utils/DomUtils.ts
- yarn.lock
In rare occasions, when using special characters in a string (ex.: ü),
the Base 64 value contains the '/' character, which is not URL query
string friendly and was previously not URI encoded.
This PR makes sure that every time a Base 64 value is used in a query
string, it's also URI encoded to make sure '/' character is not part of the query string.
Please note that the server must decode (deqoute) the query string
before decoding its Base 64 value.
> Use URI Encoding to encode Base 64 query string

- src/components/molecules/MainDetailsTable/MainDetailsTable.tsx
Previously, the source's instance name was used for the destination's
instance name in the migration results table.
This is fixed by this PR, which uses the instance `id` or `instance_name`
of the destination.
> Show the destination instance ID in migr. result

- src/@types/Instance.ts
- src/components/molecules/MainDetailsTable/MainDetailsTable.tsx
- src/components/molecules/PropertiesTable/PropertiesTable.tsx
- src/components/organisms/AssessmentDetailsContent/AssessmentDetailsContent.tsx
- src/components/organisms/MainDetails/MainDetails.tsx
- src/components/organisms/ReplicaMigrationOptions/ReplicaMigrationOptions.tsx
- src/components/organisms/WizardInstances/WizardInstances.tsx
- src/components/organisms/WizardNetworks/WizardNetworks.tsx
- src/components/organisms/WizardOptions/WizardOptions.tsx
- src/components/organisms/WizardScripts/WizardScripts.tsx
- src/components/organisms/WizardStorage/WizardStorage.tsx
- src/components/organisms/WizardSummary/WizardSummary.tsx
- src/components/pages/AssessmentDetailsPage/AssessmentDetailsPage.tsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.tsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.tsx
- src/components/pages/ReplicasPage/ReplicasPage.tsx
- src/components/pages/WizardPage/WizardPage.tsx
- src/plugins/endpoint/default/OptionsSchemaPlugin.ts
- src/sources/InstanceSource.ts
- src/sources/WizardSource.ts
- src/stores/InstanceStore.ts
- src/stores/WizardStore.ts
When displaying instances, a unique value will also be displayed (which
may be either `instance_name` or `id`).
That same unique value will also be used for all API requests where an
instance needs to be provided.
Previously, the unique value sent was `instance_name`, if available, or
just `name`, if not.
> Add support for duplicated instance names

- src/components/pages/WizardPage/WizardPage.tsx
- src/plugins/endpoint/default/OptionsSchemaPlugin.ts
- src/sources/WizardSource.ts
Execute now options were set incorrectly when creating a replica or
migration: they were set to "destination_environment" property, instead
of the "migration" or "replica" root object.
> Fix an issue where execute options were incorrect

- src/utils/ApiCaller.ts
When cancelling an API request, the app's production build would
interpret the cancellation as an error, due to the fact that the
production build minimizes the class' names.
Solved by using a different method to find out if the error was an
actual error or just a canceled request.
> Fix occasional UI 'Error setting up request' alert

- src/components/organisms/MigrationDetailsContent/MigrationDetailsContent.tsx
- src/components/organisms/ReplicaDetailsContent/ReplicaDetailsContent.tsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.tsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.tsx
- src/stores/ReplicaStore.ts
Fixes an issue where when going from a loaded replica details page back
to the replica list and then to another replica details page, the header
from the previous details page would briefly bee shown. The same applies
to migrations.
Fixes an issue where, while the details page is being loaded, clicking
on 'Executions' / 'Tasks' link would lead to an invalid page.
> Fix loading issues in repl. / migr. details pages

- package.json
- src/@types/Instance.ts
- src/@types/MainItem.ts
- src/components/organisms/EditReplica/EditReplica.tsx
- src/components/organisms/ReplicaMigrationOptions/ReplicaMigrationOptions.tsx
- src/components/organisms/WizardPageContent/WizardPageContent.tsx
- src/components/organisms/WizardScripts/WizardScripts.tsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.tsx
- src/components/pages/MigrationsPage/MigrationsPage.tsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.tsx
- src/components/pages/ReplicasPage/ReplicasPage.tsx
- src/constants.ts
- src/plugins/endpoint/default/OptionsSchemaPlugin.ts
- src/plugins/endpoint/openstack/OptionsSchemaPlugin.ts
- src/plugins/endpoint/ovm/OptionsSchemaPlugin.ts
- src/sources/MigrationSource.ts
- src/sources/ReplicaSource.ts
- src/sources/WizardSource.ts
- src/stores/MigrationStore.ts
User scripts are now stored in migration body, so the UI must send them
when recreating it.
> Send 'user_scripts' when recreating migration CORWEB-248

- src/@types/Licence.ts
- src/components/organisms/Licence/Licence.tsx
- src/components/pages/AboutModal/AboutModal.tsx
- src/sources/LincenceSource.ts
- src/stores/LicenceStore.ts
- src/utils/ApiLogger.ts
This should facilitate an easier way to copy and paste the installation
ID and the licencing server version when issuing a new licence.
> Add license version to appliance ID

- src/components/organisms/EndpointDetailsContent/EndpointDetailsContent.tsx
- src/sources/EndpointSource.ts
Sometimes, when visiting the endpoint details page, the loading
animation would be shown, even though the connection info was already
loaded.
> Fix endpoint details loading animation

- src/@types/Instance.ts
- src/@types/MainItem.ts
- src/components/organisms/EditReplica/EditReplica.tsx
- src/components/organisms/ReplicaMigrationOptions/ReplicaMigrationOptions.tsx
- src/components/organisms/WizardPageContent/WizardPageContent.tsx
- src/components/organisms/WizardScripts/WizardScripts.tsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.tsx
- src/components/pages/MigrationsPage/MigrationsPage.tsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.tsx
- src/components/pages/ReplicasPage/ReplicasPage.tsx
- src/plugins/endpoint/default/OptionsSchemaPlugin.ts
- src/plugins/endpoint/openstack/OptionsSchemaPlugin.ts
- src/plugins/endpoint/ovm/OptionsSchemaPlugin.ts
- src/sources/MigrationSource.ts
- src/sources/ReplicaSource.ts
- src/sources/WizardSource.ts
- src/stores/MigrationStore.ts
Removing the uploaded scripts translates to sending `null` value to the
server where the script content string would be.
This applies to editing the user scripts when editing a replica,
creating and recreating a migration, if a script was previously added.
> Add ability to remove the uploaded user scripts CORWEB-248

- .eslintrc
Previous default was 100. Since the setting also overrides some other
previous default values, the previous default values are also included
so that nothing else should change.
> Increase eslint code max line length to 150

- src/components/molecules/MainListItem/MainListItem.tsx
- src/components/organisms/EditReplica/EditReplica.tsx
- src/components/organisms/MainDetails/MainDetails.tsx
- src/components/organisms/WizardOptions/WizardOptions.tsx
- src/components/organisms/WizardPageContent/WizardPageContent.tsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.tsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.tsx
- src/components/pages/WizardPage/WizardPage.tsx
- src/plugins/endpoint/default/OptionsSchemaPlugin.ts
- src/sources/MigrationSource.ts
- src/sources/ReplicaSource.ts
- src/sources/WizardSource.ts
Instead of instance ID, the "notes" field is used, if available, to
display the replica / migration list item title.
The "notes" field is prepopulated when creating a replica / migration
with the selected instance(s) names.
The "notes" field can also be edited after the transfer item has been
created.
> Use the "notes" field as transfer item title CORWEB-249

- src/@types/Network.ts
- src/components/organisms/AssessmentDetailsContent/AssessmentDetailsContent.tsx
- src/components/organisms/EditReplica/EditReplica.tsx
- src/components/organisms/WizardNetworks/WizardNetworks.tsx
- src/components/organisms/WizardSummary/WizardSummary.tsx
- src/plugins/endpoint/default/OptionsSchemaPlugin.ts
- src/sources/AssessmentSource.ts
Fixes an issue where if the target network of a replica was no longer
found, networking mapping couldn't be updated.
This fixes the issue, allowing editing a replica's network mapping even
if the target network is no longer available.
> Fix unable to edit network map if missing target

- src/components/organisms/WizardOptions/WizardOptions.tsx
- src/components/pages/WizardPage/WizardPage.tsx
- src/sources/WizardSource.ts
- src/stores/WizardStore.ts
When multiple instances are selected and "Separate / VM" is checked, the
title ("notes" field) is set automatically based on each of the names of
the selected instances.
In this case, the "Title" field is disabled and can be re-enabled when
unchecking "Separate / VM".
> Use automatic Title for replicas with separate/VM COR-270

- src/components/organisms/EditReplica/EditReplica.tsx
- src/sources/EndpointSource.ts
- src/stores/EndpointStore.ts
If some destination options fields are changed (the ones specified in
config.ts as extra-options `requiredFields` or `relistFields`), the
networks and storage will reload when editing a replica or when
recreating a migration.
> Reload mappings if destination options are changed CORWEB-255

- config.ts
- src/@types/Config.ts
- src/components/organisms/ReplicaMigrationOptions/ReplicaMigrationOptions.tsx
- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.tsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.tsx
- src/components/pages/ReplicasPage/ReplicasPage.tsx
- src/stores/MigrationStore.ts
It is now possible to set the 'clone_disk' option for VMWare target. The
API will send the user an error if necessary.
> Enable VMWare target 'clone_disk' option

- src/components/organisms/EndpointDetailsContent/EndpointDetailsContent.tsx
Now, the transfer item list ('USED IN REPLICAS/MIGRATIONS' field), is
wrapped in a scrollable container when it gets too long.
Also, the transfer item notes field is used, using the same name
function used everywhere else.
> Fix transfer list too long in endpoint det. page

- src/components/pages/MigrationDetailsPage/MigrationDetailsPage.tsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.tsx
- src/sources/MigrationSource.ts
- src/sources/ReplicaSource.ts
- src/stores/EndpointStore.ts
- src/stores/InstanceStore.ts
- src/stores/MigrationStore.ts
- src/stores/ProviderStore.ts
- src/stores/ReplicaStore.ts
The replica / migration details page loading flow has been improved so
that, in rare cases, it could no longer show info from a different one.
It also fixes the rare cases where the "Endpoint Missing" placeholder
was erroneously shown.
> Improve transfer items details page loading flow CORWEB-251

- src/components/organisms/ReplicaDetailsContent/ReplicaDetailsContent.tsx
Fixes an issue where the 'Executions' and 'Schedule' links are invalid
while the replica details are being loaded when on the Replica Details
page.
> Fix replica details executions URL while loading

- src/plugins/endpoint/default/OptionsSchemaPlugin.ts
- src/plugins/endpoint/vmware_vsphere/OptionsSchemaPlugin.ts
The vmware plugin options were not being parsed due to an error caused
by a missing function. The missing function was added to the vmware
plugin.
Some TS errors were also fixed.
> Fix vmware plugin options not being parsed

- src/components/organisms/EditReplica/EditReplica.tsx
The Update button will now turn into an 'Updating ...' loading button
while the update replica request is being processed.
> Show updating feedback when Editing Replica

- src/sources/InstanceSource.ts
- src/stores/InstanceStore.ts
Previously, the UI entered an infinite loop if there was an instance
with no ID and that instance was the last in the chunk of instances
returned for an endpoint.
With this commit, if there are instances with no ID, they are skipped
and an error is shown in the UI with their name.
This commit also lays the groundwork for future instance validation.
> Add instance with no ID protection

- .eslintrc
- .vscode/settings.json
- src/components/organisms/EditReplica/EditReplica.tsx
- src/components/organisms/WizardPageContent/WizardPageContent.tsx
- src/components/organisms/WizardStorage/WizardStorage.tsx
- src/components/organisms/WizardStorage/story.tsx
- src/components/pages/WizardPage/WizardPage.tsx
- src/stores/EndpointStore.ts
If no storage backends are found or if the request fails, the user can
now retry the request.
There's now also a 'loading storage' indicator to actually see if the
storage request is actually being processed.
> Improve Wizard Storage loading UX

- .githooks/pre-commit
- src/components/molecules/ActionDropdown/ActionDropdown.tsx
- src/components/pages/ReplicaDetailsPage/ReplicaDetailsPage.tsx
The loading animation is shown next to the Edit link while the replica
info is being loaded and the Edit link is disabled.
> Show loading icon in replica details actions menu

- src/components/organisms/FilterList/FilterList.tsx
- src/components/pages/ReplicasPage/ReplicasPage.tsx
Previously, a GET /schedules request was made for every replica, every
few seconds. Now, the requests are made only for the visible replicas
(replicas that are visible in the list through filtering and / or
pagination).
> Reduce the number of replica GET /schedules reqs.

- src/components/atoms/CopyValue/CopyValue.tsx
- src/components/organisms/DashboardContent/modules/LicenceModule/LicenceModule.tsx
If the user doesn't have a licence, the appliance ID is shown in the
Dashboard licence module. It is now trimmed to fix an issue where
scrollbars may appear.
> Trim the licence appliance id shown in Dashboard

- src/components/atoms/Logo/Logo.tsx
When on the Login page, clicking on the Coriolis logo will no longer
redirect.
> Fix the Coriolis logo link from the Login page

- src/utils/KeyboardManager.ts
Since 'keyCode' is deprecated, we use 'key' instead for keyboards
events.
> Remove deprecated 'keyCode' property usage

- src/stores/ProviderStore.ts
- src/utils/ApiCaller.ts
- src/utils/ObjectUtils.ts
Sometimes when opening the edit endpoint modal and immediately starting
to edit a field, the field would revert to its initial value. This
doesn’t happen if the user waits a few seconds before starting to edit a
field.
This was caused by a concurrency issue between requests and fixed by no
longer making the requests if they are already in progress.
> Fix endpoint fields reverting to previous values

- webpack.prod.js
This will give better call stacks when throwing errors, thus making it
easier to identify production build errors.
> Add high quality source maps to production builds

- src/components/modules/DashboardModule/DashboardContent/DashboardContent.tsx
- src/components/modules/DashboardModule/DashboardLicence/DashboardLicence.tsx
The licence module will no longer display the top text with the earliest
and latest licence expiration dates and will no longer display the
lifetime fields for replicas and migrations.
> Simplify dashboard's licence module

- .vscode/launch.json
- .vscode/settings.json
- src/@types/Field.ts
- src/components/modules/TransferModule/TransferItemModal/TransferItemModal.tsx
- src/components/modules/WizardModule/WizardOptions/WizardOptions.tsx
- src/components/modules/WizardModule/WizardPageContent/WizardPageContent.tsx
- src/components/smart/WizardPage/WizardPage.tsx
- src/components/ui/Dropdowns/AutocompleteDropdown/AutocompleteDropdown.tsx
- src/components/ui/Dropdowns/Dropdown/Dropdown.tsx
- src/components/ui/FieldInput/FieldInput.tsx
- src/components/ui/InfoIcon/InfoIcon.tsx
- src/components/ui/PropertiesTable/PropertiesTable.tsx
- src/plugins/aws/OptionsSchemaPlugin.ts
- src/plugins/azure/OptionsSchemaPlugin.ts
- src/plugins/default/OptionsSchemaPlugin.ts
- src/plugins/index.ts
- src/plugins/openstack/OptionsSchemaPlugin.ts
- src/plugins/ovirt/OptionsSchemaPlugin.ts
- src/plugins/ovm/OptionsSchemaPlugin.ts
- src/sources/MigrationSource.ts
- src/sources/ProviderSource.ts
- src/sources/Schemas.ts
- src/stores/MinionPoolStore.ts
- src/stores/ProviderStore.ts
- src/stores/WizardStore.ts
The following changes are now applied:
- The Next button is no longer disabled in wizard source and destination
options when required field values are missing.
- When clicking the Next button, the required fields with missing values
are *highlighted* and the wizard doesn't go to the next page.
- As part of *highlighting* a field, a small label is displayed besides
that field saying that the field is required. This label is also shown
everywhere there are required fields: new endpoint, new user etc.
> Improve UX for wizard options required fields

- src/components/ui/Lists/FilterList/FilterList.tsx
- src/components/ui/Lists/MainList/MainList.tsx
Fixes an issue where scroll would stay where it was on the previous page
when clicking the next or previous page button when on the replicas or
migrations list pages.
> Fix scroll not resetting on page change

- README.md
- babel.config.js
- src/constants.ts
- src/plugins/default/OptionsSchemaPlugin.ts
Use NODE_ENV instead to set the node environment.
NODE_MODE was used back when there was a naming conflict between the
two.
> Rename NODE_MODE env. variable

- src/components/modules/WizardModule/WizardOptions/WizardOptions.tsx
Fixes an issue where at certain browser zoom levels, horizontal scroll
might appear in the Wizard Page.
> Fix horizontal scroll appearing when zooming out

- config.ts
This is a password / secret field used by the Azure cloud provider.
> Display `client_secret` field as a password

- src/components/App.tsx
Fixes a routing typo that raises a not found error when navigating to
the Projects page.
> Fix "Projects not found" routing error

- src/components/modules/TransferModule/TransferItemModal/TransferItemModal.tsx
Fixes an issue where if a replica has an invalid network mapping object
(i.e. empty object, invalid network name), the UI wouldn't allow the
user to change it.
> Fix editing a replica with invalid network mapping

- config.ts
- src/components/modules/TransferModule/TransferItemModal/TransferItemModal.tsx
- src/components/smart/WizardPage/WizardPage.tsx
- src/stores/ProviderStore.ts
This applies to the Replica / Migration wizard.
This commit also contains reloading of options when the minion pool
migration image changes when creating a minion pool.
> Reload OCI options on migration image map change

- src/components/modules/TransferModule/TransferItemModal/TransferItemModal.tsx
Now when editing a replica the Windows image is now required if the
instance is Windows, thus keeping the same behaviour as in the replica
wizard.
> Fix Windows image not required in edit replica

- src/components/modules/TransferModule/MainDetails/MainDetails.tsx
Fixes an issue where a replica which has nested objects in its
environment and the values of those object properties are shown as IDs
instead of their label / name.
> Fix IDs displayed instead of names in details page

- src/components/modules/TransferModule/Executions/Executions.tsx
- src/components/modules/TransferModule/MigrationDetailsContent/MigrationDetailsContent.tsx
- src/components/modules/TransferModule/ReplicaDetailsContent/ReplicaDetailsContent.tsx
- src/components/modules/TransferModule/TaskItem/TaskItem.tsx
- src/components/modules/TransferModule/Tasks/Tasks.tsx
Applies to the replica and migration details pages in the executions
panel.
> Show instance name instead of ID in execution task

- src/components/modules/TransferModule/TransferItemModal/TransferItemModal.tsx
- src/utils/ObjectUtils.ts
This happens, for example, when editing a replica with Openstack as the
source provider. The issue was caused by not properly handling object
validation in the case of nested objects inside replica's source or
destination environment.
> Fix disabled 'Update' button in replica edit modal CORWEB-262

- src/components/modules/TransferModule/ReplicaDetailsContent/ReplicaDetailsContent.tsx
- src/components/modules/TransferModule/ReplicaExecutionOptions/ReplicaExecutionOptions.tsx
- src/components/modules/TransferModule/Schedule/Schedule.tsx
- src/components/modules/TransferModule/TransferItemModal/TransferItemModal.tsx
- src/components/modules/WizardModule/WizardOptions/WizardOptions.tsx
- src/components/modules/WizardModule/WizardPageContent/WizardPageContent.tsx
- src/components/smart/ReplicaDetailsPage/ReplicaDetailsPage.tsx
- src/components/smart/ReplicasPage/ReplicasPage.tsx
- src/constants.ts
Previously the execution options were disabled only when creating a bare
metal replica. Now, they are disabled everywhere where execution options
are shown for it, example: scheduling, manual execution etc.
> Disable execution options for bare metal replicas

- src/stores/MigrationStore.ts
When recreating multiple migrations simultaneously from the migrations list page, duplicated migrations might appear temporarily.
> Fix migrations appearing twice when recreating

- src/components/modules/TransferModule/TransferItemModal/TransferItemModal.tsx
The button label is now “Creating” instead of “Updating” when re-creating a migration.
> Fix button label when recreating migration

- src/sources/UserSource.ts
- src/stores/UserStore.ts
The `defaultUserDomain` option from the config file was previously ignored if a successful login was already done with a different user domain in the same browser.
This is fixed by always using the `defaultUserDomain` option when logging in, if `showUserDomainInput` is false. If `showUserDomainInput` is true, then the user domain input is shown when logging in and the behaviour is kept as it was previously, where the last successful user domain is pre-filled in the user domain input.
> Fix default user domain for Keystone UI login

- src/components/modules/TransferModule/TransferItemModal/TransferItemModal.tsx
Fixes an issue where sometimes not all environment data was sent to the API when requesting the list of networks, thus the network might return an incomplete or incorrect list.
> Fix networks not loading properly in Edit Replica

- src/components/modules/TransferModule/TransferItemModal/TransferItemModal.tsx
- src/utils/ObjectUtils.ts
The UI might previously crash when selecting a null value from a dropdown list in Edit Replica modal. This was caused by updating the global state of the replica when editing instead of the local state (the local state here is the changed replica from the Edit Replica modal).
This was fixed by cloning the global state into the local state before any changes are made.
> Fix UI crash when selecting `null` value

- src/components/modules/WizardModule/WizardOptions/WizardOptions.tsx
An unnecessary vertical scroll bar might have previously appeared in the wizard source \ target options when the last field in the list was required and highlighted with the requirement message.
> Fix a vertical scroll bar appearing in the wizard

- src/components/ui/Modal/Modal.tsx
On certain occasions a help tooltip may remain open after closing a modal.
To reproduce the issue prior to this fix, hover the mouse over an Edit Replica modal help icon and press the ESC key.
This fix manually removes any tooltip when closing any modal.
> Hide tooltip when closing a modal popup

- src/plugins/default/OptionsSchemaPlugin.ts
Previously, when editing a replica by completely removing the value from a field, the empty field was ignored when building the request body with the updated data.
This is now fixed by using the current state of the replica to determine whether the updated field value should be sent even if it is empty.
> Fix updating field to empty value in edit replica

- src/components/modules/WizardModule/WizardSummary/WizardSummary.tsx
Made the wizard summary page have its two columns of equal size. Previously, the right column was smaller.
Adjusted the column widths to be equal to provide a better visual balance to the page.
> Equalize wizard summary page columns

- src/components/modules/TransferModule/ReplicaMigrationOptions/ReplicaMigrationOptions.tsx
- src/components/smart/ReplicaDetailsPage/ReplicaDetailsPage.tsx
This commit updates the behavior of the recreate migration modal to show a loading message while the migration is being created. Previously, the modal was instantly dismissed and a notification was shown that the migration was created, requiring the user to click a redirect button for redirection.
With this change, the modal will remain open and display a loading message until the migration has finished being created, at which point it will automatically redirect to the migration status page.
This improves the user experience by providing more information and reducing the number of steps required to view the migration status.
> Show loading message in recreate migration modal

- README.md
Resolved issue with missing images for the Coriolis logo and GitHub action status badge in the readme file. The images are now correctly displayed in the readme.
> Fix missing images in `README.md`

- src/components/modules/WizardModule/WizardInstances/WizardInstances.tsx
This applies to Wizard instances selection screen.
> Show GB when instance RAM is larger than 1GB

- src/@types/MetalHub.ts
- src/components/modules/MetalHubModule/MetalHubServerDetailsContent/MetalHubServerDetailsContent.tsx
Previously, the UI could crash when accessing the Bare Metal server details page if it encountered a missing property in the Bare Metal object. This issue has been resolved by marking the relevant properties as optional.
> Support optional properties in BM server object

- src/stores/EndpointStore.ts
- src/stores/LogStore.ts
When zipping files using the JSZip library, by default, files are not compressed when they are zipped (`store` compression level is used). The JSZip options have now been updated to actually compress the files.
The affected processes are the logs and endpoints downloads.
> Fix zipped files not being compressed

- src/components/smart/WizardPage/WizardPage.tsx
The 'Next' button in the Wizard Options interface is disabled after an options API call fails, and does not automatically re-enable even after the API call eventually succeeds.
> Fix 'Next' button disabled in Wizard Options

- src/components/modules/DashboardModule/DashboardLicence/DashboardLicence.tsx
The dashboard's licence module layout may not have properly adapted to varying viewport widths. To test this, resize the browser and launch the app at different widths to observe its responsiveness.
Note that this fix only applies to the situation where the licence has expired.
> Improve the dashboard’s licence module layout

- src/components/modules/WizardModule/WizardStorage/WizardStorage.tsx
The path display logic can be tested with Openstack as a source. Previously, the path would be erroneously truncated to the first and second elements of the disk name array. With this change, the path is correctly displayed as the first and last elements of the disk name array.
> Update WizardStorage style format and path display

- src/components/modules/TransferModule/TaskItem/TaskItem.tsx
- src/components/modules/TransferModule/TaskItem/story.tsx
- src/components/modules/TransferModule/Tasks/Tasks.tsx
Example: "Deploy Os Morphing Resources" -> "Deploy OS Morphing Resources"
Also replaces the IDs of task names with the actual names in task's "Depends On" field.
> Fix "Os" spelling in migration tasks names

- src/components/smart/LogStreamPage/LogStreamPage.tsx
- src/components/smart/LogsPage/LogsPage.tsx
- src/components/smart/LogsPage/StreamText.tsx
This commit adds search functionality to the logs live feed, allowing
users to live stream lines based on their search query.
Changes:
- Added `search` state to `LogsPage.tsx` and passed it down to
`StreamText.tsx`.
- Added `SearchInput` component to `StreamText.tsx` header.
- Updated `liveFeed` prop in `LogsPage.tsx` to filter logs based on the
search query.
- Refactored the styling of log severity pills in `StreamText.tsx`.
> Add search functionality to logs live feed

- src/components/smart/EndpointsPage/EndpointsPage.tsx
The endpoints page might crash if the provider label is not set. This can happen depending on the order of the endpoints in the list. This commit fixes the crash by checking for the label before trying to render it.
> Fix endpoints page crash on no provider label

- src/@types/MainItem.ts
- src/components/smart/MigrationsPage/MigrationsPage.tsx
- src/components/smart/ReplicasPage/ReplicasPage.tsx
Fixes an issue where search functionality was not working when replicas or migrations had a notes field with a null value. Previously, it was assumed that the notes field could only contain a string.
> Fix search in Replicas and Migrations pages

- src/components/modules/TransferModule/TaskItem/TaskItem.tsx
- src/components/ui/StatusComponents/StatusPill/StatusPill.tsx
The status of a task is set to WARNING if any of the task's progress updates begin with "WARNING". Otherwise, the status returned by the API remains unchanged.
> Add "WARNING" as a task dynamic status

- .dockerignore
- Dockerfile
- A new base image (Node) was adopted, replacing the previous one (Ubuntu).
- This new base image eliminates the need for installing Node and Yarn.
- The latest Node LTS version, which is now 18, has been implemented.
- The new Node version defaults to using OpenSSL 3. However, due to incompatibility issues with some dependencies (`webpack`), the legacy version (1.1.1) is retained instead.
> Docker file upgrade Node version from 16 to 18

- src/plugins/default/OptionsSchemaPlugin.ts
Fixes an issue in the 'Edit Replica' modal where setting a field's value to 'null' could cause the client to send an invalid value to the API.
> Fix reset to null in Edit Replica modal

- src/components/modules/TransferModule/TaskItem/TaskItem.tsx
The new line character `\n` is now supported through the use of the CSS property `white-space: pre-line`.
> Add new line character support in Task Item comp.

- src/components/modules/TransferModule/MainDetails/MainDetails.tsx
When editing a Replica while looking at its MainDetails screen and changing a value, the MainDetails page in the background automatically re-renders on each value selection, and crashed if the value was edited to be null.
> Fix crash in MainDetails component on Replica edit.

- cypress/fixtures/licences/appliance-status.json
Fixes the licence status fixture in integration testing. This change will fix the failing dashboard test due to expired licence fixture.
> Fix licensing status fixture

- src/plugins/openstack/OptionsSchemaPlugin.ts
This PR changes openstack schema parser to add default field values for `replica_export_mechanism`.
> [Openstack] Fill default field value for replica_export_mechanism

- config.ts
- package.json
- src/@types/Config.ts
- src/components/App.tsx
This patch adds the `IdleTimer` component to the main App component,
which will be configured to time out if the user is inactive on the
app pages. On timeout, the user gets automatically logged out.
This functionality is disabled by default, and can be configured using
the `inactiveSessionTimeout` configuration option.
> Automatically log out from inactive user sessions

- config.ts
- cypress/e2e/endpoints/endpoints-list.cy.ts
- src/@types/Config.ts
- src/components/modules/MinionModule/MinionPoolDetailsContent/MinionPoolEvents.spec.tsx
- src/components/modules/MinionModule/MinionPoolDetailsContent/MinionPoolEvents.tsx
- src/components/modules/WizardModule/WizardInstances/WizardInstances.tsx
- src/components/smart/EndpointsPage/EndpointsPage.tsx
- src/components/smart/ProjectsPage/ProjectsPage.tsx
- src/components/smart/UsersPage/UsersPage.tsx
- src/components/ui/Lists/FilterList/FilterList.spec.tsx
- src/components/ui/Lists/FilterList/FilterList.tsx
- src/components/ui/Pagination/ArrowPagination/ArrowPagination.spec.tsx
- src/components/ui/Pagination/ArrowPagination/ArrowPagination.tsx
- src/components/ui/Pagination/ArrowPagination/package.json
- src/components/ui/Pagination/NumberedPagination/NumberedPagination.spec.tsx
- src/components/ui/Pagination/NumberedPagination/NumberedPagination.tsx
- src/components/ui/Pagination/NumberedPagination/package.json
- src/components/ui/Pagination/package.json
This PR includes the following changes:
- Rename `Pagination` component to `ArrowPagination`;
- Add new `NumberedPagination` component with `page counts` and `navigation`;
- Fix `e2e/unit` tests;
- Add test cases for `NumberedPagination` component.
> Add `numbered pagination` component with `page navigation` controls

- cypress/e2e/transfers/transfers-list.cy.ts
- src/components/smart/DeploymentDetailsPage/DeploymentDetailsPage.tsx
- src/components/smart/TransferDetailsPage/TransferDetailsPage.tsx
- src/sources/DeploymentSource.ts
- src/sources/TransferSource.ts
- src/stores/DeploymentStore.ts
- src/stores/TransferStore.ts
* When `transfers` or `deployments` complete successfully and `source VMs` are subsequently removed, it fails to load VM details and `mappings` due to API errors when trying to fetch from the `source endpoint`.
* Enable `include_task_info` optional parameter in `API URL` to allow fetching task details even when source VMs are missing.
> Use stored VM info for completed `transfers/deployments` when source VMs are removed
